// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apispec.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiSpec = `-- name: CreateApiSpec :one
INSERT INTO api_specs (workspace_id, collection_id, name, spec_url, spec_hash, base_url_var, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateApiSpecParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
	Name         string      `json:"name"`
	SpecUrl      string      `json:"spec_url"`
	SpecHash     string      `json:"spec_hash"`
	BaseUrlVar   string      `json:"base_url_var"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateApiSpec(ctx context.Context, arg CreateApiSpecParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createApiSpec,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.Name,
		arg.SpecUrl,
		arg.SpecHash,
		arg.BaseUrlVar,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createPushedApiSpec = `-- name: CreatePushedApiSpec :one
INSERT INTO api_specs (workspace_id, collection_id, name, source_type, spec_hash, spec_content, created_by)
VALUES ($1, $2, $3, 'push', $4, $5, $6)
RETURNING id
`

type CreatePushedApiSpecParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
	Name         string      `json:"name"`
	SpecHash     string      `json:"spec_hash"`
	SpecContent  []byte      `json:"spec_content"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePushedApiSpec(ctx context.Context, arg CreatePushedApiSpecParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPushedApiSpec,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.Name,
		arg.SpecHash,
		arg.SpecContent,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSpecCollection = `-- name: CreateSpecCollection :one
INSERT INTO collections (workspace_id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSpecCollectionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSpecCollection(ctx context.Context, arg CreateSpecCollectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSpecCollection, arg.WorkspaceID, arg.Name, arg.CreatedBy)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUploadedApiSpec = `-- name: CreateUploadedApiSpec :one
INSERT INTO api_specs (workspace_id, collection_id, name, source_type, spec_url, spec_hash, spec_content, base_url_var, created_by)
VALUES ($1, $2, $3, 'upload', '', $4, $5, 'baseUrl', $6)
RETURNING id
`

type CreateUploadedApiSpecParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
	Name         string      `json:"name"`
	SpecHash     string      `json:"spec_hash"`
	SpecContent  []byte      `json:"spec_content"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateUploadedApiSpec(ctx context.Context, arg CreateUploadedApiSpecParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUploadedApiSpec,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.Name,
		arg.SpecHash,
		arg.SpecContent,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteApiSpec = `-- name: DeleteApiSpec :exec
DELETE FROM api_specs
WHERE id = $1
`

func (q *Queries) DeleteApiSpec(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiSpec, id)
	return err
}

const getApiSpec = `-- name: GetApiSpec :one
SELECT id, workspace_id, collection_id, name, source_type, spec_url, spec_hash, base_url_var, last_synced_at, created_at, updated_at
FROM api_specs
WHERE id = $1
`

type GetApiSpecRow struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	CollectionID pgtype.UUID        `json:"collection_id"`
	Name         string             `json:"name"`
	SourceType   string             `json:"source_type"`
	SpecUrl      string             `json:"spec_url"`
	SpecHash     string             `json:"spec_hash"`
	BaseUrlVar   string             `json:"base_url_var"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetApiSpec(ctx context.Context, id pgtype.UUID) (GetApiSpecRow, error) {
	row := q.db.QueryRow(ctx, getApiSpec, id)
	var i GetApiSpecRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CollectionID,
		&i.Name,
		&i.SourceType,
		&i.SpecUrl,
		&i.SpecHash,
		&i.BaseUrlVar,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApiSpecIDByWorkspaceAndName = `-- name: GetApiSpecIDByWorkspaceAndName :one
SELECT id
FROM api_specs
WHERE workspace_id = $1 AND name = $2
LIMIT 1
`

type GetApiSpecIDByWorkspaceAndNameParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
}

func (q *Queries) GetApiSpecIDByWorkspaceAndName(ctx context.Context, arg GetApiSpecIDByWorkspaceAndNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getApiSpecIDByWorkspaceAndName, arg.WorkspaceID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getApiSpecRow = `-- name: GetApiSpecRow :one
SELECT id, workspace_id, collection_id, name, COALESCE(source_type, 'url'), spec_url, spec_hash, base_url_var, spec_content
FROM api_specs
WHERE id = $1
`

type GetApiSpecRowRow struct {
	ID           pgtype.UUID `json:"id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
	Name         string      `json:"name"`
	SourceType   string      `json:"source_type"`
	SpecUrl      string      `json:"spec_url"`
	SpecHash     string      `json:"spec_hash"`
	BaseUrlVar   string      `json:"base_url_var"`
	SpecContent  []byte      `json:"spec_content"`
}

func (q *Queries) GetApiSpecRow(ctx context.Context, id pgtype.UUID) (GetApiSpecRowRow, error) {
	row := q.db.QueryRow(ctx, getApiSpecRow, id)
	var i GetApiSpecRowRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CollectionID,
		&i.Name,
		&i.SourceType,
		&i.SpecUrl,
		&i.SpecHash,
		&i.BaseUrlVar,
		&i.SpecContent,
	)
	return i, err
}

const listApiSpecs = `-- name: ListApiSpecs :many
SELECT id, workspace_id, collection_id, name, source_type, spec_url, spec_hash, base_url_var, last_synced_at, created_at, updated_at
FROM api_specs
WHERE workspace_id = $1
ORDER BY name
`

type ListApiSpecsRow struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	CollectionID pgtype.UUID        `json:"collection_id"`
	Name         string             `json:"name"`
	SourceType   string             `json:"source_type"`
	SpecUrl      string             `json:"spec_url"`
	SpecHash     string             `json:"spec_hash"`
	BaseUrlVar   string             `json:"base_url_var"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListApiSpecs(ctx context.Context, workspaceID pgtype.UUID) ([]ListApiSpecsRow, error) {
	rows, err := q.db.Query(ctx, listApiSpecs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiSpecsRow{}
	for rows.Next() {
		var i ListApiSpecsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CollectionID,
			&i.Name,
			&i.SourceType,
			&i.SpecUrl,
			&i.SpecHash,
			&i.BaseUrlVar,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncedRequestsBySpec = `-- name: ListSyncedRequestsBySpec :many
SELECT id, COALESCE(source_operation_id, ''), COALESCE(source_op_hash, ''), name, method, url
FROM requests
WHERE source_spec_id = $1
`

type ListSyncedRequestsBySpecRow struct {
	ID                pgtype.UUID `json:"id"`
	SourceOperationID string      `json:"source_operation_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
}

func (q *Queries) ListSyncedRequestsBySpec(ctx context.Context, sourceSpecID pgtype.UUID) ([]ListSyncedRequestsBySpecRow, error) {
	rows, err := q.db.Query(ctx, listSyncedRequestsBySpec, sourceSpecID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSyncedRequestsBySpecRow{}
	for rows.Next() {
		var i ListSyncedRequestsBySpecRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceOperationID,
			&i.SourceOpHash,
			&i.Name,
			&i.Method,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiSpecAfterSync = `-- name: UpdateApiSpecAfterSync :exec
UPDATE api_specs
SET spec_hash = $1, last_synced_at = now(), updated_at = now()
WHERE id = $2
`

type UpdateApiSpecAfterSyncParams struct {
	SpecHash string      `json:"spec_hash"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApiSpecAfterSync(ctx context.Context, arg UpdateApiSpecAfterSyncParams) error {
	_, err := q.db.Exec(ctx, updateApiSpecAfterSync, arg.SpecHash, arg.ID)
	return err
}

const updateApiSpecBaseURLVar = `-- name: UpdateApiSpecBaseURLVar :exec
UPDATE api_specs
SET base_url_var = $1, updated_at = now()
WHERE id = $2
`

type UpdateApiSpecBaseURLVarParams struct {
	BaseUrlVar string      `json:"base_url_var"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApiSpecBaseURLVar(ctx context.Context, arg UpdateApiSpecBaseURLVarParams) error {
	_, err := q.db.Exec(ctx, updateApiSpecBaseURLVar, arg.BaseUrlVar, arg.ID)
	return err
}

const updateApiSpecCollectionID = `-- name: UpdateApiSpecCollectionID :exec
UPDATE api_specs
SET collection_id = $1, updated_at = now()
WHERE id = $2
`

type UpdateApiSpecCollectionIDParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApiSpecCollectionID(ctx context.Context, arg UpdateApiSpecCollectionIDParams) error {
	_, err := q.db.Exec(ctx, updateApiSpecCollectionID, arg.CollectionID, arg.ID)
	return err
}

const updateApiSpecLastSynced = `-- name: UpdateApiSpecLastSynced :exec
UPDATE api_specs
SET last_synced_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateApiSpecLastSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateApiSpecLastSynced, id)
	return err
}

const updateApiSpecLastSyncedOnly = `-- name: UpdateApiSpecLastSyncedOnly :exec
UPDATE api_specs
SET last_synced_at = now()
WHERE id = $1
`

func (q *Queries) UpdateApiSpecLastSyncedOnly(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateApiSpecLastSyncedOnly, id)
	return err
}

const updateApiSpecName = `-- name: UpdateApiSpecName :exec
UPDATE api_specs
SET name = $1, updated_at = now()
WHERE id = $2
`

type UpdateApiSpecNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApiSpecName(ctx context.Context, arg UpdateApiSpecNameParams) error {
	_, err := q.db.Exec(ctx, updateApiSpecName, arg.Name, arg.ID)
	return err
}

const updateApiSpecReupload = `-- name: UpdateApiSpecReupload :exec
UPDATE api_specs
SET spec_content = $1, spec_hash = $2, source_type = 'upload', updated_at = now()
WHERE id = $3
`

type UpdateApiSpecReuploadParams struct {
	SpecContent []byte      `json:"spec_content"`
	SpecHash    string      `json:"spec_hash"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApiSpecReupload(ctx context.Context, arg UpdateApiSpecReuploadParams) error {
	_, err := q.db.Exec(ctx, updateApiSpecReupload, arg.SpecContent, arg.SpecHash, arg.ID)
	return err
}

const updateApiSpecURL = `-- name: UpdateApiSpecURL :exec
UPDATE api_specs
SET spec_url = $1, updated_at = now()
WHERE id = $2
`

type UpdateApiSpecURLParams struct {
	SpecUrl string      `json:"spec_url"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateApiSpecURL(ctx context.Context, arg UpdateApiSpecURLParams) error {
	_, err := q.db.Exec(ctx, updateApiSpecURL, arg.SpecUrl, arg.ID)
	return err
}

const updatePushedApiSpec = `-- name: UpdatePushedApiSpec :exec
UPDATE api_specs
SET spec_content = $1, spec_hash = $2, source_type = 'push', updated_at = now()
WHERE id = $3
`

type UpdatePushedApiSpecParams struct {
	SpecContent []byte      `json:"spec_content"`
	SpecHash    string      `json:"spec_hash"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePushedApiSpec(ctx context.Context, arg UpdatePushedApiSpecParams) error {
	_, err := q.db.Exec(ctx, updatePushedApiSpec, arg.SpecContent, arg.SpecHash, arg.ID)
	return err
}

const updateSyncedRequest = `-- name: UpdateSyncedRequest :exec
UPDATE requests
SET method = $1,
    url = $2,
    headers = $3,
    params = $4,
    path_vars = $5,
    source_op_hash = $6,
    api_doc = $7,
    description = CASE WHEN docs_overridden THEN description ELSE $8 END,
    body = CASE WHEN 'body' = ANY(overridden_fields) THEN body ELSE $9 END,
    updated_at = now()
WHERE source_spec_id = $10 AND source_operation_id = $11
`

type UpdateSyncedRequestParams struct {
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	SourceOpHash      string      `json:"source_op_hash"`
	ApiDoc            []byte      `json:"api_doc"`
	Description       string      `json:"description"`
	Body              []byte      `json:"body"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
}

func (q *Queries) UpdateSyncedRequest(ctx context.Context, arg UpdateSyncedRequestParams) error {
	_, err := q.db.Exec(ctx, updateSyncedRequest,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.SourceOpHash,
		arg.ApiDoc,
		arg.Description,
		arg.Body,
		arg.SourceSpecID,
		arg.SourceOperationID,
	)
	return err
}

const upsertApiSpecEnvironmentURL = `-- name: UpsertApiSpecEnvironmentURL :exec
INSERT INTO api_spec_environment_urls (api_spec_id, environment_id, base_url)
VALUES ($1, $2, $3)
ON CONFLICT (api_spec_id, environment_id) DO UPDATE SET base_url = EXCLUDED.base_url
`

type UpsertApiSpecEnvironmentURLParams struct {
	ApiSpecID     pgtype.UUID `json:"api_spec_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	BaseUrl       string      `json:"base_url"`
}

func (q *Queries) UpsertApiSpecEnvironmentURL(ctx context.Context, arg UpsertApiSpecEnvironmentURLParams) error {
	_, err := q.db.Exec(ctx, upsertApiSpecEnvironmentURL, arg.ApiSpecID, arg.EnvironmentID, arg.BaseUrl)
	return err
}
