// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const getRefreshTokenWithUser = `-- name: GetRefreshTokenWithUser :one
SELECT rt.user_id, u.email, rt.expires_at
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
`

type GetRefreshTokenWithUserRow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetRefreshTokenWithUser(ctx context.Context, tokenHash string) (GetRefreshTokenWithUserRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenWithUser, tokenHash)
	var i GetRefreshTokenWithUserRow
	err := row.Scan(&i.UserID, &i.Email, &i.ExpiresAt)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, password_hash, display_name
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  string      `json:"display_name"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.DisplayName)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT email, display_name
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.Email, &i.DisplayName)
	return i, err
}

const getWorkspaceMemberRole = `-- name: GetWorkspaceMemberRole :one
SELECT role::text
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkspaceMemberRole(ctx context.Context, arg GetWorkspaceMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberRole, arg.WorkspaceID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
