// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brunosync.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrunoSource = `-- name: CreateBrunoSource :one
INSERT INTO bruno_sources (workspace_id, name, config, access_token_encrypted, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateBrunoSourceParams struct {
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
	Name                 string      `json:"name"`
	Config               []byte      `json:"config"`
	AccessTokenEncrypted *string     `json:"access_token_encrypted"`
	CreatedBy            pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateBrunoSource(ctx context.Context, arg CreateBrunoSourceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createBrunoSource,
		arg.WorkspaceID,
		arg.Name,
		arg.Config,
		arg.AccessTokenEncrypted,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteBrunoSource = `-- name: DeleteBrunoSource :exec
DELETE FROM bruno_sources
WHERE id = $1 AND workspace_id = $2
`

type DeleteBrunoSourceParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteBrunoSource(ctx context.Context, arg DeleteBrunoSourceParams) error {
	_, err := q.db.Exec(ctx, deleteBrunoSource, arg.ID, arg.WorkspaceID)
	return err
}

const deleteBrunoSyncedCollectionsBySource = `-- name: DeleteBrunoSyncedCollectionsBySource :exec
DELETE FROM collections
WHERE bruno_source_id = $1
`

func (q *Queries) DeleteBrunoSyncedCollectionsBySource(ctx context.Context, brunoSourceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBrunoSyncedCollectionsBySource, brunoSourceID)
	return err
}

const deleteBrunoSyncedCollectionsNotInPaths = `-- name: DeleteBrunoSyncedCollectionsNotInPaths :execrows
DELETE FROM collections
WHERE bruno_source_id = $1
  AND source_path <> ''
  AND NOT (source_path = ANY($2::text[]))
`

type DeleteBrunoSyncedCollectionsNotInPathsParams struct {
	BrunoSourceID pgtype.UUID `json:"bruno_source_id"`
	KeepPaths     []string    `json:"keep_paths"`
}

func (q *Queries) DeleteBrunoSyncedCollectionsNotInPaths(ctx context.Context, arg DeleteBrunoSyncedCollectionsNotInPathsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBrunoSyncedCollectionsNotInPaths, arg.BrunoSourceID, arg.KeepPaths)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBrunoSyncedRequestsNotInPaths = `-- name: DeleteBrunoSyncedRequestsNotInPaths :execrows
DELETE FROM requests
WHERE bruno_source_id = $1
  AND source_path <> ''
  AND NOT (source_path = ANY($2::text[]))
`

type DeleteBrunoSyncedRequestsNotInPathsParams struct {
	BrunoSourceID pgtype.UUID `json:"bruno_source_id"`
	KeepPaths     []string    `json:"keep_paths"`
}

func (q *Queries) DeleteBrunoSyncedRequestsNotInPaths(ctx context.Context, arg DeleteBrunoSyncedRequestsNotInPathsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBrunoSyncedRequestsNotInPaths, arg.BrunoSourceID, arg.KeepPaths)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBrunoSource = `-- name: GetBrunoSource :one
SELECT id, workspace_id, collection_id, name, config, access_token_encrypted, last_synced_at, created_at
FROM bruno_sources
WHERE id = $1 AND workspace_id = $2
`

type GetBrunoSourceParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetBrunoSourceRow struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	Name                 string             `json:"name"`
	Config               []byte             `json:"config"`
	AccessTokenEncrypted *string            `json:"access_token_encrypted"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetBrunoSource(ctx context.Context, arg GetBrunoSourceParams) (GetBrunoSourceRow, error) {
	row := q.db.QueryRow(ctx, getBrunoSource, arg.ID, arg.WorkspaceID)
	var i GetBrunoSourceRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CollectionID,
		&i.Name,
		&i.Config,
		&i.AccessTokenEncrypted,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBrunoSourceForSync = `-- name: GetBrunoSourceForSync :one
SELECT id, workspace_id, collection_id, name, config, access_token_encrypted, last_synced_at
FROM bruno_sources
WHERE id = $1
`

type GetBrunoSourceForSyncRow struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	Name                 string             `json:"name"`
	Config               []byte             `json:"config"`
	AccessTokenEncrypted *string            `json:"access_token_encrypted"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) GetBrunoSourceForSync(ctx context.Context, id pgtype.UUID) (GetBrunoSourceForSyncRow, error) {
	row := q.db.QueryRow(ctx, getBrunoSourceForSync, id)
	var i GetBrunoSourceForSyncRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CollectionID,
		&i.Name,
		&i.Config,
		&i.AccessTokenEncrypted,
		&i.LastSyncedAt,
	)
	return i, err
}

const insertBrunoSyncedCollection = `-- name: InsertBrunoSyncedCollection :one
INSERT INTO collections (
    workspace_id, parent_id, name, description, sort_order, variables, headers, auth,
    pre_request_script, test_script, source_path, bruno_source_id, created_by
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13
)
RETURNING id
`

type InsertBrunoSyncedCollectionParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ParentID         pgtype.UUID `json:"parent_id"`
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	SortOrder        int32       `json:"sort_order"`
	Variables        []byte      `json:"variables"`
	Headers          []byte      `json:"headers"`
	Auth             []byte      `json:"auth"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	SourcePath       string      `json:"source_path"`
	BrunoSourceID    pgtype.UUID `json:"bruno_source_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertBrunoSyncedCollection(ctx context.Context, arg InsertBrunoSyncedCollectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertBrunoSyncedCollection,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.Variables,
		arg.Headers,
		arg.Auth,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SourcePath,
		arg.BrunoSourceID,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertBrunoSyncedRequest = `-- name: InsertBrunoSyncedRequest :exec
INSERT INTO requests (
    collection_id, name, method, url, headers, params, path_vars, body, auth, settings,
    pre_request_script, test_script, sort_order, description,
    source_path, bruno_source_id, source_operation_id, source_op_hash, created_by
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17, $18, $19
)
`

type InsertBrunoSyncedRequestParams struct {
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	Settings          []byte      `json:"settings"`
	PreRequestScript  string      `json:"pre_request_script"`
	TestScript        string      `json:"test_script"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	SourcePath        string      `json:"source_path"`
	BrunoSourceID     pgtype.UUID `json:"bruno_source_id"`
	SourceOperationID string      `json:"source_operation_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	CreatedBy         pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertBrunoSyncedRequest(ctx context.Context, arg InsertBrunoSyncedRequestParams) error {
	_, err := q.db.Exec(ctx, insertBrunoSyncedRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SortOrder,
		arg.Description,
		arg.SourcePath,
		arg.BrunoSourceID,
		arg.SourceOperationID,
		arg.SourceOpHash,
		arg.CreatedBy,
	)
	return err
}

const listBrunoSources = `-- name: ListBrunoSources :many
SELECT id, workspace_id, collection_id, name, config, access_token_encrypted, last_synced_at, created_at
FROM bruno_sources
WHERE workspace_id = $1
ORDER BY name
`

type ListBrunoSourcesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	Name                 string             `json:"name"`
	Config               []byte             `json:"config"`
	AccessTokenEncrypted *string            `json:"access_token_encrypted"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListBrunoSources(ctx context.Context, workspaceID pgtype.UUID) ([]ListBrunoSourcesRow, error) {
	rows, err := q.db.Query(ctx, listBrunoSources, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrunoSourcesRow{}
	for rows.Next() {
		var i ListBrunoSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CollectionID,
			&i.Name,
			&i.Config,
			&i.AccessTokenEncrypted,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrunoSyncedCollections = `-- name: ListBrunoSyncedCollections :many
SELECT id, parent_id, source_path, name
FROM collections
WHERE bruno_source_id = $1
`

type ListBrunoSyncedCollectionsRow struct {
	ID         pgtype.UUID `json:"id"`
	ParentID   pgtype.UUID `json:"parent_id"`
	SourcePath string      `json:"source_path"`
	Name       string      `json:"name"`
}

func (q *Queries) ListBrunoSyncedCollections(ctx context.Context, brunoSourceID pgtype.UUID) ([]ListBrunoSyncedCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listBrunoSyncedCollections, brunoSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrunoSyncedCollectionsRow{}
	for rows.Next() {
		var i ListBrunoSyncedCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SourcePath,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrunoSyncedRequests = `-- name: ListBrunoSyncedRequests :many
SELECT id, collection_id, source_path, COALESCE(source_op_hash, ''), name
FROM requests
WHERE bruno_source_id = $1 AND source_path <> ''
`

type ListBrunoSyncedRequestsRow struct {
	ID           pgtype.UUID `json:"id"`
	CollectionID pgtype.UUID `json:"collection_id"`
	SourcePath   string      `json:"source_path"`
	SourceOpHash string      `json:"source_op_hash"`
	Name         string      `json:"name"`
}

func (q *Queries) ListBrunoSyncedRequests(ctx context.Context, brunoSourceID pgtype.UUID) ([]ListBrunoSyncedRequestsRow, error) {
	rows, err := q.db.Query(ctx, listBrunoSyncedRequests, brunoSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrunoSyncedRequestsRow{}
	for rows.Next() {
		var i ListBrunoSyncedRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.SourcePath,
			&i.SourceOpHash,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrunoSource = `-- name: UpdateBrunoSource :exec
UPDATE bruno_sources
SET name = COALESCE($1, name),
    config = COALESCE($2, config),
    access_token_encrypted = COALESCE($3, access_token_encrypted)
WHERE id = $4 AND workspace_id = $5
`

type UpdateBrunoSourceParams struct {
	Name                 *string     `json:"name"`
	Config               []byte      `json:"config"`
	AccessTokenEncrypted *string     `json:"access_token_encrypted"`
	ID                   pgtype.UUID `json:"id"`
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateBrunoSource(ctx context.Context, arg UpdateBrunoSourceParams) error {
	_, err := q.db.Exec(ctx, updateBrunoSource,
		arg.Name,
		arg.Config,
		arg.AccessTokenEncrypted,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateBrunoSourceCollectionID = `-- name: UpdateBrunoSourceCollectionID :exec
UPDATE bruno_sources
SET collection_id = $1
WHERE id = $2
`

type UpdateBrunoSourceCollectionIDParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBrunoSourceCollectionID(ctx context.Context, arg UpdateBrunoSourceCollectionIDParams) error {
	_, err := q.db.Exec(ctx, updateBrunoSourceCollectionID, arg.CollectionID, arg.ID)
	return err
}

const updateBrunoSourceLastSynced = `-- name: UpdateBrunoSourceLastSynced :exec
UPDATE bruno_sources
SET last_synced_at = now()
WHERE id = $1
`

func (q *Queries) UpdateBrunoSourceLastSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateBrunoSourceLastSynced, id)
	return err
}

const updateBrunoSyncedCollection = `-- name: UpdateBrunoSyncedCollection :exec
UPDATE collections
SET name = $1,
    description = $2,
    sort_order = $3,
    variables = $4,
    headers = $5,
    auth = $6,
    pre_request_script = $7,
    test_script = $8,
    parent_id = $9,
    updated_at = now()
WHERE id = $10 AND bruno_source_id = $11
`

type UpdateBrunoSyncedCollectionParams struct {
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	SortOrder        int32       `json:"sort_order"`
	Variables        []byte      `json:"variables"`
	Headers          []byte      `json:"headers"`
	Auth             []byte      `json:"auth"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	ParentID         pgtype.UUID `json:"parent_id"`
	ID               pgtype.UUID `json:"id"`
	BrunoSourceID    pgtype.UUID `json:"bruno_source_id"`
}

func (q *Queries) UpdateBrunoSyncedCollection(ctx context.Context, arg UpdateBrunoSyncedCollectionParams) error {
	_, err := q.db.Exec(ctx, updateBrunoSyncedCollection,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.Variables,
		arg.Headers,
		arg.Auth,
		arg.PreRequestScript,
		arg.TestScript,
		arg.ParentID,
		arg.ID,
		arg.BrunoSourceID,
	)
	return err
}

const updateBrunoSyncedRequest = `-- name: UpdateBrunoSyncedRequest :exec
UPDATE requests
SET name = $1,
    method = $2,
    url = $3,
    headers = $4,
    params = $5,
    path_vars = $6,
    body = CASE WHEN 'body' = ANY(overridden_fields) THEN body ELSE $7 END,
    auth = $8,
    pre_request_script = $9,
    test_script = $10,
    sort_order = $11,
    description = $12,
    collection_id = $13,
    source_op_hash = $14,
    source_operation_id = $15,
    updated_at = now()
WHERE id = $16 AND bruno_source_id = $17
`

type UpdateBrunoSyncedRequestParams struct {
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	PreRequestScript  string      `json:"pre_request_script"`
	TestScript        string      `json:"test_script"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	CollectionID      pgtype.UUID `json:"collection_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	SourceOperationID string      `json:"source_operation_id"`
	ID                pgtype.UUID `json:"id"`
	BrunoSourceID     pgtype.UUID `json:"bruno_source_id"`
}

func (q *Queries) UpdateBrunoSyncedRequest(ctx context.Context, arg UpdateBrunoSyncedRequestParams) error {
	_, err := q.db.Exec(ctx, updateBrunoSyncedRequest,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SortOrder,
		arg.Description,
		arg.CollectionID,
		arg.SourceOpHash,
		arg.SourceOperationID,
		arg.ID,
		arg.BrunoSourceID,
	)
	return err
}
