// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collection.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const collectionExists = `-- name: CollectionExists :one
SELECT EXISTS(SELECT 1 FROM collections WHERE id = $1)
`

func (q *Queries) CollectionExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, collectionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (
    workspace_id, parent_id, name, description, sort_order, variables,
    headers, auth, presets, proxy, client_certificates, secrets,
    pre_request_script, test_script, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12,
    $13, $14, $15
) RETURNING id
`

type CreateCollectionParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	ParentID           pgtype.UUID `json:"parent_id"`
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	SortOrder          int32       `json:"sort_order"`
	Variables          []byte      `json:"variables"`
	Headers            []byte      `json:"headers"`
	Auth               []byte      `json:"auth"`
	Presets            []byte      `json:"presets"`
	Proxy              []byte      `json:"proxy"`
	ClientCertificates []byte      `json:"client_certificates"`
	Secrets            []byte      `json:"secrets"`
	PreRequestScript   string      `json:"pre_request_script"`
	TestScript         string      `json:"test_script"`
	CreatedBy          pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.Variables,
		arg.Headers,
		arg.Auth,
		arg.Presets,
		arg.Proxy,
		arg.ClientCertificates,
		arg.Secrets,
		arg.PreRequestScript,
		arg.TestScript,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections
WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, workspace_id, parent_id, name, description, sort_order, variables,
       headers, auth, presets, proxy, client_certificates, secrets,
       pre_request_script, test_script
FROM collections
WHERE id = $1
`

type GetCollectionRow struct {
	ID                 pgtype.UUID `json:"id"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	ParentID           pgtype.UUID `json:"parent_id"`
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	SortOrder          int32       `json:"sort_order"`
	Variables          []byte      `json:"variables"`
	Headers            []byte      `json:"headers"`
	Auth               []byte      `json:"auth"`
	Presets            []byte      `json:"presets"`
	Proxy              []byte      `json:"proxy"`
	ClientCertificates []byte      `json:"client_certificates"`
	Secrets            []byte      `json:"secrets"`
	PreRequestScript   string      `json:"pre_request_script"`
	TestScript         string      `json:"test_script"`
}

func (q *Queries) GetCollection(ctx context.Context, id pgtype.UUID) (GetCollectionRow, error) {
	row := q.db.QueryRow(ctx, getCollection, id)
	var i GetCollectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.Variables,
		&i.Headers,
		&i.Auth,
		&i.Presets,
		&i.Proxy,
		&i.ClientCertificates,
		&i.Secrets,
		&i.PreRequestScript,
		&i.TestScript,
	)
	return i, err
}

const getCollectionAuth = `-- name: GetCollectionAuth :one
SELECT auth
FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionAuth(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCollectionAuth, id)
	var auth []byte
	err := row.Scan(&auth)
	return auth, err
}

const getCollectionContext = `-- name: GetCollectionContext :one
SELECT workspace_id, pre_request_script, test_script
FROM collections
WHERE id = $1
`

type GetCollectionContextRow struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
}

func (q *Queries) GetCollectionContext(ctx context.Context, id pgtype.UUID) (GetCollectionContextRow, error) {
	row := q.db.QueryRow(ctx, getCollectionContext, id)
	var i GetCollectionContextRow
	err := row.Scan(&i.WorkspaceID, &i.PreRequestScript, &i.TestScript)
	return i, err
}

const getCollectionForCatalogShare = `-- name: GetCollectionForCatalogShare :one
SELECT name, description
FROM collections
WHERE id = $1 AND workspace_id = $2
`

type GetCollectionForCatalogShareParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetCollectionForCatalogShareRow struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) GetCollectionForCatalogShare(ctx context.Context, arg GetCollectionForCatalogShareParams) (GetCollectionForCatalogShareRow, error) {
	row := q.db.QueryRow(ctx, getCollectionForCatalogShare, arg.ID, arg.WorkspaceID)
	var i GetCollectionForCatalogShareRow
	err := row.Scan(&i.Name, &i.Description)
	return i, err
}

const getCollectionForExport = `-- name: GetCollectionForExport :one
SELECT name, description, variables, headers, auth, pre_request_script, test_script
FROM collections
WHERE id = $1
`

type GetCollectionForExportRow struct {
	Name             string `json:"name"`
	Description      string `json:"description"`
	Variables        []byte `json:"variables"`
	Headers          []byte `json:"headers"`
	Auth             []byte `json:"auth"`
	PreRequestScript string `json:"pre_request_script"`
	TestScript       string `json:"test_script"`
}

func (q *Queries) GetCollectionForExport(ctx context.Context, id pgtype.UUID) (GetCollectionForExportRow, error) {
	row := q.db.QueryRow(ctx, getCollectionForExport, id)
	var i GetCollectionForExportRow
	err := row.Scan(
		&i.Name,
		&i.Description,
		&i.Variables,
		&i.Headers,
		&i.Auth,
		&i.PreRequestScript,
		&i.TestScript,
	)
	return i, err
}

const getCollectionNameDescription = `-- name: GetCollectionNameDescription :one
SELECT name, description
FROM collections
WHERE id = $1
`

type GetCollectionNameDescriptionRow struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) GetCollectionNameDescription(ctx context.Context, id pgtype.UUID) (GetCollectionNameDescriptionRow, error) {
	row := q.db.QueryRow(ctx, getCollectionNameDescription, id)
	var i GetCollectionNameDescriptionRow
	err := row.Scan(&i.Name, &i.Description)
	return i, err
}

const getCollectionParentID = `-- name: GetCollectionParentID :one
SELECT parent_id
FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionParentID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCollectionParentID, id)
	var parent_id pgtype.UUID
	err := row.Scan(&parent_id)
	return parent_id, err
}

const getCollectionVariables = `-- name: GetCollectionVariables :one
SELECT variables
FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionVariables(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCollectionVariables, id)
	var variables []byte
	err := row.Scan(&variables)
	return variables, err
}

const getCollectionWorkspaceForMember = `-- name: GetCollectionWorkspaceForMember :one
SELECT c.workspace_id
FROM collections c
JOIN workspace_members wm ON wm.workspace_id = c.workspace_id AND wm.user_id = $1
WHERE c.id = $2
`

type GetCollectionWorkspaceForMemberParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

func (q *Queries) GetCollectionWorkspaceForMember(ctx context.Context, arg GetCollectionWorkspaceForMemberParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCollectionWorkspaceForMember, arg.UserID, arg.CollectionID)
	var workspace_id pgtype.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getCollectionWorkspaceID = `-- name: GetCollectionWorkspaceID :one
SELECT workspace_id
FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionWorkspaceID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCollectionWorkspaceID, id)
	var workspace_id pgtype.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listCatalogCollections = `-- name: ListCatalogCollections :many
SELECT id, name, description, parent_id, sort_order
FROM collections
WHERE workspace_id = $1
ORDER BY sort_order, name
`

type ListCatalogCollectionsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	ParentID    pgtype.UUID `json:"parent_id"`
	SortOrder   int32       `json:"sort_order"`
}

func (q *Queries) ListCatalogCollections(ctx context.Context, workspaceID pgtype.UUID) ([]ListCatalogCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogCollections, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogCollectionsRow{}
	for rows.Next() {
		var i ListCatalogCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ParentID,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogCollectionsByID = `-- name: ListCatalogCollectionsByID :many
SELECT id, name, description
FROM collections
WHERE workspace_id = $1 AND id = $2
ORDER BY sort_order, name
`

type ListCatalogCollectionsByIDParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

type ListCatalogCollectionsByIDRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) ListCatalogCollectionsByID(ctx context.Context, arg ListCatalogCollectionsByIDParams) ([]ListCatalogCollectionsByIDRow, error) {
	rows, err := q.db.Query(ctx, listCatalogCollectionsByID, arg.WorkspaceID, arg.CollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogCollectionsByIDRow{}
	for rows.Next() {
		var i ListCatalogCollectionsByIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildCollectionIDs = `-- name: ListChildCollectionIDs :many
SELECT id
FROM collections
WHERE parent_id = $1
`

func (q *Queries) ListChildCollectionIDs(ctx context.Context, parentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listChildCollectionIDs, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByParent = `-- name: ListCollectionsByParent :many
SELECT id, workspace_id, parent_id, name, description, sort_order, variables,
       headers, auth, presets, proxy, client_certificates, secrets,
       pre_request_script, test_script
FROM collections
WHERE parent_id = $1
`

type ListCollectionsByParentRow struct {
	ID                 pgtype.UUID `json:"id"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	ParentID           pgtype.UUID `json:"parent_id"`
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	SortOrder          int32       `json:"sort_order"`
	Variables          []byte      `json:"variables"`
	Headers            []byte      `json:"headers"`
	Auth               []byte      `json:"auth"`
	Presets            []byte      `json:"presets"`
	Proxy              []byte      `json:"proxy"`
	ClientCertificates []byte      `json:"client_certificates"`
	Secrets            []byte      `json:"secrets"`
	PreRequestScript   string      `json:"pre_request_script"`
	TestScript         string      `json:"test_script"`
}

func (q *Queries) ListCollectionsByParent(ctx context.Context, parentID pgtype.UUID) ([]ListCollectionsByParentRow, error) {
	rows, err := q.db.Query(ctx, listCollectionsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsByParentRow{}
	for rows.Next() {
		var i ListCollectionsByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.Variables,
			&i.Headers,
			&i.Auth,
			&i.Presets,
			&i.Proxy,
			&i.ClientCertificates,
			&i.Secrets,
			&i.PreRequestScript,
			&i.TestScript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByWorkspace = `-- name: ListCollectionsByWorkspace :many
SELECT id, workspace_id, parent_id, name, description, sort_order, variables,
       headers, auth, presets, proxy, client_certificates, secrets,
       pre_request_script, test_script
FROM collections
WHERE workspace_id = $1
ORDER BY sort_order, name
`

type ListCollectionsByWorkspaceRow struct {
	ID                 pgtype.UUID `json:"id"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	ParentID           pgtype.UUID `json:"parent_id"`
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	SortOrder          int32       `json:"sort_order"`
	Variables          []byte      `json:"variables"`
	Headers            []byte      `json:"headers"`
	Auth               []byte      `json:"auth"`
	Presets            []byte      `json:"presets"`
	Proxy              []byte      `json:"proxy"`
	ClientCertificates []byte      `json:"client_certificates"`
	Secrets            []byte      `json:"secrets"`
	PreRequestScript   string      `json:"pre_request_script"`
	TestScript         string      `json:"test_script"`
}

func (q *Queries) ListCollectionsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListCollectionsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listCollectionsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionsByWorkspaceRow{}
	for rows.Next() {
		var i ListCollectionsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.Variables,
			&i.Headers,
			&i.Auth,
			&i.Presets,
			&i.Proxy,
			&i.ClientCertificates,
			&i.Secrets,
			&i.PreRequestScript,
			&i.TestScript,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderCollection = `-- name: ReorderCollection :exec
UPDATE collections
SET parent_id = $1,
    sort_order = $2,
    updated_at = now()
WHERE id = $3
`

type ReorderCollectionParams struct {
	ParentID  pgtype.UUID `json:"parent_id"`
	SortOrder int32       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) ReorderCollection(ctx context.Context, arg ReorderCollectionParams) error {
	_, err := q.db.Exec(ctx, reorderCollection, arg.ParentID, arg.SortOrder, arg.ID)
	return err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections
SET name = $1,
    description = $2,
    parent_id = $3,
    sort_order = $4,
    variables = $5,
    headers = $6,
    auth = $7,
    presets = $8,
    proxy = $9,
    client_certificates = $10,
    secrets = $11,
    pre_request_script = $12,
    test_script = $13,
    updated_at = now()
WHERE id = $14
`

type UpdateCollectionParams struct {
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	ParentID           pgtype.UUID `json:"parent_id"`
	SortOrder          int32       `json:"sort_order"`
	Variables          []byte      `json:"variables"`
	Headers            []byte      `json:"headers"`
	Auth               []byte      `json:"auth"`
	Presets            []byte      `json:"presets"`
	Proxy              []byte      `json:"proxy"`
	ClientCertificates []byte      `json:"client_certificates"`
	Secrets            []byte      `json:"secrets"`
	PreRequestScript   string      `json:"pre_request_script"`
	TestScript         string      `json:"test_script"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.Exec(ctx, updateCollection,
		arg.Name,
		arg.Description,
		arg.ParentID,
		arg.SortOrder,
		arg.Variables,
		arg.Headers,
		arg.Auth,
		arg.Presets,
		arg.Proxy,
		arg.ClientCertificates,
		arg.Secrets,
		arg.PreRequestScript,
		arg.TestScript,
		arg.ID,
	)
	return err
}
