// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagram.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDiagramRequestLink = `-- name: AddDiagramRequestLink :exec
INSERT INTO diagram_request_links (diagram_id, request_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddDiagramRequestLinkParams struct {
	DiagramID pgtype.UUID `json:"diagram_id"`
	RequestID pgtype.UUID `json:"request_id"`
}

func (q *Queries) AddDiagramRequestLink(ctx context.Context, arg AddDiagramRequestLinkParams) error {
	_, err := q.db.Exec(ctx, addDiagramRequestLink, arg.DiagramID, arg.RequestID)
	return err
}

const createWorkspaceDiagram = `-- name: CreateWorkspaceDiagram :one
INSERT INTO workspace_diagrams (workspace_id, slug, title, content, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, slug, title, content, created_by, created_at, updated_at
`

type CreateWorkspaceDiagramParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Content     []byte      `json:"content"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWorkspaceDiagram(ctx context.Context, arg CreateWorkspaceDiagramParams) (WorkspaceDiagram, error) {
	row := q.db.QueryRow(ctx, createWorkspaceDiagram,
		arg.WorkspaceID,
		arg.Slug,
		arg.Title,
		arg.Content,
		arg.CreatedBy,
	)
	var i WorkspaceDiagram
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceDiagram = `-- name: DeleteWorkspaceDiagram :exec
DELETE FROM workspace_diagrams
WHERE workspace_id = $1 AND slug = $2
`

type DeleteWorkspaceDiagramParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

func (q *Queries) DeleteWorkspaceDiagram(ctx context.Context, arg DeleteWorkspaceDiagramParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceDiagram, arg.WorkspaceID, arg.Slug)
	return err
}

const getWorkspaceDiagramBySlug = `-- name: GetWorkspaceDiagramBySlug :one
SELECT id, workspace_id, slug, title, content, created_by, created_at, updated_at
FROM workspace_diagrams
WHERE workspace_id = $1 AND slug = $2
`

type GetWorkspaceDiagramBySlugParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

func (q *Queries) GetWorkspaceDiagramBySlug(ctx context.Context, arg GetWorkspaceDiagramBySlugParams) (WorkspaceDiagram, error) {
	row := q.db.QueryRow(ctx, getWorkspaceDiagramBySlug, arg.WorkspaceID, arg.Slug)
	var i WorkspaceDiagram
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDiagramRequestLinks = `-- name: ListDiagramRequestLinks :many
SELECT r.id, r.name, r.method, r.url, c.workspace_id, w.name AS workspace_name
FROM diagram_request_links drl
JOIN requests r ON r.id = drl.request_id
JOIN collections c ON c.id = r.collection_id
JOIN workspaces w ON w.id = c.workspace_id
WHERE drl.diagram_id = $1
`

type ListDiagramRequestLinksRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Method        string      `json:"method"`
	Url           string      `json:"url"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	WorkspaceName string      `json:"workspace_name"`
}

func (q *Queries) ListDiagramRequestLinks(ctx context.Context, diagramID pgtype.UUID) ([]ListDiagramRequestLinksRow, error) {
	rows, err := q.db.Query(ctx, listDiagramRequestLinks, diagramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiagramRequestLinksRow{}
	for rows.Next() {
		var i ListDiagramRequestLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.WorkspaceID,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceDiagrams = `-- name: ListWorkspaceDiagrams :many
SELECT id, workspace_id, slug, title, updated_at
FROM workspace_diagrams
WHERE workspace_id = $1
ORDER BY title ASC
`

type ListWorkspaceDiagramsRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkspaceDiagrams(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceDiagramsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDiagrams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceDiagramsRow{}
	for rows.Next() {
		var i ListWorkspaceDiagramsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDiagramRequestLink = `-- name: RemoveDiagramRequestLink :exec
DELETE FROM diagram_request_links
WHERE diagram_id = $1 AND request_id = $2
`

type RemoveDiagramRequestLinkParams struct {
	DiagramID pgtype.UUID `json:"diagram_id"`
	RequestID pgtype.UUID `json:"request_id"`
}

func (q *Queries) RemoveDiagramRequestLink(ctx context.Context, arg RemoveDiagramRequestLinkParams) error {
	_, err := q.db.Exec(ctx, removeDiagramRequestLink, arg.DiagramID, arg.RequestID)
	return err
}

const updateWorkspaceDiagram = `-- name: UpdateWorkspaceDiagram :one
UPDATE workspace_diagrams
SET title = COALESCE($1, title),
    content = COALESCE($2, content),
    updated_at = now()
WHERE workspace_id = $3 AND slug = $4
RETURNING id, workspace_id, slug, title, content, created_by, created_at, updated_at
`

type UpdateWorkspaceDiagramParams struct {
	Title       *string     `json:"title"`
	Content     []byte      `json:"content"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

func (q *Queries) UpdateWorkspaceDiagram(ctx context.Context, arg UpdateWorkspaceDiagramParams) (WorkspaceDiagram, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceDiagram,
		arg.Title,
		arg.Content,
		arg.WorkspaceID,
		arg.Slug,
	)
	var i WorkspaceDiagram
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workspaceDiagramSlugExists = `-- name: WorkspaceDiagramSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM workspace_diagrams
    WHERE workspace_id = $1 AND slug = $2
) AS exists
`

type WorkspaceDiagramSlugExistsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

func (q *Queries) WorkspaceDiagramSlugExists(ctx context.Context, arg WorkspaceDiagramSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceDiagramSlugExists, arg.WorkspaceID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
