// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doclinks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingDocLinkSuggestions = `-- name: CountPendingDocLinkSuggestions :one
SELECT COUNT(*)::int
FROM doc_link_suggestions
WHERE workspace_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingDocLinkSuggestions(ctx context.Context, workspaceID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingDocLinkSuggestions, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteStalePendingDocLinkSuggestions = `-- name: DeleteStalePendingDocLinkSuggestions :exec
DELETE FROM doc_link_suggestions
WHERE workspace_id = $1
  AND status = 'pending'
  AND id <> ALL($2::uuid[])
`

type DeleteStalePendingDocLinkSuggestionsParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	KeepIds     []pgtype.UUID `json:"keep_ids"`
}

func (q *Queries) DeleteStalePendingDocLinkSuggestions(ctx context.Context, arg DeleteStalePendingDocLinkSuggestionsParams) error {
	_, err := q.db.Exec(ctx, deleteStalePendingDocLinkSuggestions, arg.WorkspaceID, arg.KeepIds)
	return err
}

const getDocLinkSuggestion = `-- name: GetDocLinkSuggestion :one
SELECT s.id, s.workspace_id, s.workspace_doc_id, s.request_id, s.reason, s.confidence, s.status
FROM doc_link_suggestions s
WHERE s.id = $1 AND s.workspace_id = $2
`

type GetDocLinkSuggestionParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetDocLinkSuggestionRow struct {
	ID             pgtype.UUID `json:"id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	WorkspaceDocID pgtype.UUID `json:"workspace_doc_id"`
	RequestID      pgtype.UUID `json:"request_id"`
	Reason         string      `json:"reason"`
	Confidence     string      `json:"confidence"`
	Status         string      `json:"status"`
}

func (q *Queries) GetDocLinkSuggestion(ctx context.Context, arg GetDocLinkSuggestionParams) (GetDocLinkSuggestionRow, error) {
	row := q.db.QueryRow(ctx, getDocLinkSuggestion, arg.ID, arg.WorkspaceID)
	var i GetDocLinkSuggestionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkspaceDocID,
		&i.RequestID,
		&i.Reason,
		&i.Confidence,
		&i.Status,
	)
	return i, err
}

const listDocLinkSuggestions = `-- name: ListDocLinkSuggestions :many
SELECT s.id, s.workspace_doc_id, s.request_id, s.reason, s.confidence, s.evidence, s.status, s.created_at,
       d.title AS doc_title, d.slug AS doc_slug,
       r.name AS request_name, r.method, r.url,
       COALESCE(r.source_operation_id, ''), c.name AS collection_name
FROM doc_link_suggestions s
JOIN workspace_docs d ON d.id = s.workspace_doc_id
JOIN requests r ON r.id = s.request_id
JOIN collections c ON c.id = r.collection_id
WHERE s.workspace_id = $1
  AND s.status = $2
ORDER BY
  CASE s.confidence WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
  d.title, r.name
`

type ListDocLinkSuggestionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Status      string      `json:"status"`
}

type ListDocLinkSuggestionsRow struct {
	ID                pgtype.UUID        `json:"id"`
	WorkspaceDocID    pgtype.UUID        `json:"workspace_doc_id"`
	RequestID         pgtype.UUID        `json:"request_id"`
	Reason            string             `json:"reason"`
	Confidence        string             `json:"confidence"`
	Evidence          []byte             `json:"evidence"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DocTitle          string             `json:"doc_title"`
	DocSlug           string             `json:"doc_slug"`
	RequestName       string             `json:"request_name"`
	Method            string             `json:"method"`
	Url               string             `json:"url"`
	SourceOperationID string             `json:"source_operation_id"`
	CollectionName    string             `json:"collection_name"`
}

func (q *Queries) ListDocLinkSuggestions(ctx context.Context, arg ListDocLinkSuggestionsParams) ([]ListDocLinkSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listDocLinkSuggestions, arg.WorkspaceID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocLinkSuggestionsRow{}
	for rows.Next() {
		var i ListDocLinkSuggestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceDocID,
			&i.RequestID,
			&i.Reason,
			&i.Confidence,
			&i.Evidence,
			&i.Status,
			&i.CreatedAt,
			&i.DocTitle,
			&i.DocSlug,
			&i.RequestName,
			&i.Method,
			&i.Url,
			&i.SourceOperationID,
			&i.CollectionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocLinkSuggestionsForAnalyze = `-- name: ListDocLinkSuggestionsForAnalyze :many
SELECT id, workspace_doc_id, request_id, status
FROM doc_link_suggestions
WHERE workspace_id = $1
`

type ListDocLinkSuggestionsForAnalyzeRow struct {
	ID             pgtype.UUID `json:"id"`
	WorkspaceDocID pgtype.UUID `json:"workspace_doc_id"`
	RequestID      pgtype.UUID `json:"request_id"`
	Status         string      `json:"status"`
}

func (q *Queries) ListDocLinkSuggestionsForAnalyze(ctx context.Context, workspaceID pgtype.UUID) ([]ListDocLinkSuggestionsForAnalyzeRow, error) {
	rows, err := q.db.Query(ctx, listDocLinkSuggestionsForAnalyze, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocLinkSuggestionsForAnalyzeRow{}
	for rows.Next() {
		var i ListDocLinkSuggestionsForAnalyzeRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceDocID,
			&i.RequestID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDocLinkSuggestionsByDoc = `-- name: ListPendingDocLinkSuggestionsByDoc :many
SELECT s.id, s.request_id, s.reason, s.confidence, s.evidence,
       r.name AS request_name, r.method, r.url,
       COALESCE(r.source_operation_id, ''), c.name AS collection_name
FROM doc_link_suggestions s
JOIN requests r ON r.id = s.request_id
JOIN collections c ON c.id = r.collection_id
WHERE s.workspace_doc_id = $1
  AND s.workspace_id = $2
  AND s.status = 'pending'
ORDER BY r.name
`

type ListPendingDocLinkSuggestionsByDocParams struct {
	WorkspaceDocID pgtype.UUID `json:"workspace_doc_id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
}

type ListPendingDocLinkSuggestionsByDocRow struct {
	ID                pgtype.UUID `json:"id"`
	RequestID         pgtype.UUID `json:"request_id"`
	Reason            string      `json:"reason"`
	Confidence        string      `json:"confidence"`
	Evidence          []byte      `json:"evidence"`
	RequestName       string      `json:"request_name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	SourceOperationID string      `json:"source_operation_id"`
	CollectionName    string      `json:"collection_name"`
}

func (q *Queries) ListPendingDocLinkSuggestionsByDoc(ctx context.Context, arg ListPendingDocLinkSuggestionsByDocParams) ([]ListPendingDocLinkSuggestionsByDocRow, error) {
	rows, err := q.db.Query(ctx, listPendingDocLinkSuggestionsByDoc, arg.WorkspaceDocID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingDocLinkSuggestionsByDocRow{}
	for rows.Next() {
		var i ListPendingDocLinkSuggestionsByDocRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Reason,
			&i.Confidence,
			&i.Evidence,
			&i.RequestName,
			&i.Method,
			&i.Url,
			&i.SourceOperationID,
			&i.CollectionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocLinkSuggestionStatus = `-- name: UpdateDocLinkSuggestionStatus :exec
UPDATE doc_link_suggestions
SET status = $1,
    reviewed_at = now(),
    reviewed_by = $2
WHERE id = $3 AND workspace_id = $4
`

type UpdateDocLinkSuggestionStatusParams struct {
	Status      string      `json:"status"`
	ReviewedBy  pgtype.UUID `json:"reviewed_by"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateDocLinkSuggestionStatus(ctx context.Context, arg UpdateDocLinkSuggestionStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocLinkSuggestionStatus,
		arg.Status,
		arg.ReviewedBy,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const upsertDocLinkSuggestion = `-- name: UpsertDocLinkSuggestion :one
INSERT INTO doc_link_suggestions (workspace_id, workspace_doc_id, request_id, reason, confidence, evidence, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
ON CONFLICT (workspace_doc_id, request_id) DO UPDATE SET
    reason = EXCLUDED.reason,
    confidence = EXCLUDED.confidence,
    evidence = EXCLUDED.evidence,
    status = CASE
        WHEN doc_link_suggestions.status = 'rejected' THEN doc_link_suggestions.status
        ELSE 'pending'
    END,
    reviewed_at = CASE
        WHEN doc_link_suggestions.status = 'rejected' THEN doc_link_suggestions.reviewed_at
        ELSE NULL
    END,
    reviewed_by = CASE
        WHEN doc_link_suggestions.status = 'rejected' THEN doc_link_suggestions.reviewed_by
        ELSE NULL
    END
RETURNING id, workspace_id, workspace_doc_id, request_id, reason, confidence, evidence, status, created_at
`

type UpsertDocLinkSuggestionParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	WorkspaceDocID pgtype.UUID `json:"workspace_doc_id"`
	RequestID      pgtype.UUID `json:"request_id"`
	Reason         string      `json:"reason"`
	Confidence     string      `json:"confidence"`
	Evidence       []byte      `json:"evidence"`
}

type UpsertDocLinkSuggestionRow struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	WorkspaceDocID pgtype.UUID        `json:"workspace_doc_id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	Reason         string             `json:"reason"`
	Confidence     string             `json:"confidence"`
	Evidence       []byte             `json:"evidence"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertDocLinkSuggestion(ctx context.Context, arg UpsertDocLinkSuggestionParams) (UpsertDocLinkSuggestionRow, error) {
	row := q.db.QueryRow(ctx, upsertDocLinkSuggestion,
		arg.WorkspaceID,
		arg.WorkspaceDocID,
		arg.RequestID,
		arg.Reason,
		arg.Confidence,
		arg.Evidence,
	)
	var i UpsertDocLinkSuggestionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WorkspaceDocID,
		&i.RequestID,
		&i.Reason,
		&i.Confidence,
		&i.Evidence,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
