// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: docsync.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWorkspaceDocSlugConflict = `-- name: ClearWorkspaceDocSlugConflict :exec
DELETE FROM workspace_docs
WHERE workspace_id = $1
  AND slug = $2
  AND source_path <> $3
  AND doc_source_id = $4
`

type ClearWorkspaceDocSlugConflictParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
	SourcePath  string      `json:"source_path"`
	DocSourceID pgtype.UUID `json:"doc_source_id"`
}

func (q *Queries) ClearWorkspaceDocSlugConflict(ctx context.Context, arg ClearWorkspaceDocSlugConflictParams) error {
	_, err := q.db.Exec(ctx, clearWorkspaceDocSlugConflict,
		arg.WorkspaceID,
		arg.Slug,
		arg.SourcePath,
		arg.DocSourceID,
	)
	return err
}

const createDocSource = `-- name: CreateDocSource :one
INSERT INTO doc_sources (workspace_id, collection_id, name, source_type, config, access_token_encrypted, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateDocSourceParams struct {
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
	CollectionID         pgtype.UUID `json:"collection_id"`
	Name                 string      `json:"name"`
	SourceType           string      `json:"source_type"`
	Config               []byte      `json:"config"`
	AccessTokenEncrypted *string     `json:"access_token_encrypted"`
	CreatedBy            pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDocSource(ctx context.Context, arg CreateDocSourceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDocSource,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.Name,
		arg.SourceType,
		arg.Config,
		arg.AccessTokenEncrypted,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createManualDocLink = `-- name: CreateManualDocLink :one
INSERT INTO manual_doc_links (workspace_doc_id, request_id)
VALUES ($1, $2)
ON CONFLICT (workspace_doc_id, request_id) DO UPDATE SET created_at = manual_doc_links.created_at
RETURNING id, workspace_doc_id, request_id, created_at
`

type CreateManualDocLinkParams struct {
	WorkspaceDocID pgtype.UUID `json:"workspace_doc_id"`
	RequestID      pgtype.UUID `json:"request_id"`
}

func (q *Queries) CreateManualDocLink(ctx context.Context, arg CreateManualDocLinkParams) (ManualDocLink, error) {
	row := q.db.QueryRow(ctx, createManualDocLink, arg.WorkspaceDocID, arg.RequestID)
	var i ManualDocLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceDocID,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceDoc = `-- name: CreateWorkspaceDoc :one
INSERT INTO workspace_docs (workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at)
VALUES ($1, $2, $3, $4, $5, true, $6, $7, now())
RETURNING id, workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at
`

type CreateWorkspaceDocParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	Slug               string      `json:"slug"`
	Title              string      `json:"title"`
	ContentMd          string      `json:"content_md"`
	SourcePath         string      `json:"source_path"`
	LinkedOperationIds []string    `json:"linked_operation_ids"`
	LinkedRequestNames []string    `json:"linked_request_names"`
}

type CreateWorkspaceDocRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWorkspaceDoc(ctx context.Context, arg CreateWorkspaceDocParams) (CreateWorkspaceDocRow, error) {
	row := q.db.QueryRow(ctx, createWorkspaceDoc,
		arg.WorkspaceID,
		arg.Slug,
		arg.Title,
		arg.ContentMd,
		arg.SourcePath,
		arg.LinkedOperationIds,
		arg.LinkedRequestNames,
	)
	var i CreateWorkspaceDocRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.ContentMd,
		&i.SourcePath,
		&i.IsLocal,
		&i.LinkedOperationIds,
		&i.LinkedRequestNames,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocSource = `-- name: DeleteDocSource :exec
DELETE FROM doc_sources
WHERE id = $1 AND workspace_id = $2
`

type DeleteDocSourceParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteDocSource(ctx context.Context, arg DeleteDocSourceParams) error {
	_, err := q.db.Exec(ctx, deleteDocSource, arg.ID, arg.WorkspaceID)
	return err
}

const deleteLocalWorkspaceDoc = `-- name: DeleteLocalWorkspaceDoc :execrows
DELETE FROM workspace_docs
WHERE workspace_id = $1 AND slug = $2 AND is_local = true
`

type DeleteLocalWorkspaceDocParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

func (q *Queries) DeleteLocalWorkspaceDoc(ctx context.Context, arg DeleteLocalWorkspaceDocParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocalWorkspaceDoc, arg.WorkspaceID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteManualDocLink = `-- name: DeleteManualDocLink :exec
DELETE FROM manual_doc_links m
USING workspace_docs d
WHERE m.id = $1 AND m.workspace_doc_id = d.id AND d.workspace_id = $2
`

type DeleteManualDocLinkParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteManualDocLink(ctx context.Context, arg DeleteManualDocLinkParams) error {
	_, err := q.db.Exec(ctx, deleteManualDocLink, arg.ID, arg.WorkspaceID)
	return err
}

const deleteWorkspaceDocsByDocSource = `-- name: DeleteWorkspaceDocsByDocSource :exec
DELETE FROM workspace_docs
WHERE workspace_id = $1 AND doc_source_id = $2
`

type DeleteWorkspaceDocsByDocSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DocSourceID pgtype.UUID `json:"doc_source_id"`
}

func (q *Queries) DeleteWorkspaceDocsByDocSource(ctx context.Context, arg DeleteWorkspaceDocsByDocSourceParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceDocsByDocSource, arg.WorkspaceID, arg.DocSourceID)
	return err
}

const getDocSource = `-- name: GetDocSource :one
SELECT id, workspace_id, collection_id, name, source_type, config, access_token_encrypted, last_synced_at, created_at
FROM doc_sources
WHERE id = $1 AND workspace_id = $2
`

type GetDocSourceParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetDocSourceRow struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	Name                 string             `json:"name"`
	SourceType           string             `json:"source_type"`
	Config               []byte             `json:"config"`
	AccessTokenEncrypted *string            `json:"access_token_encrypted"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDocSource(ctx context.Context, arg GetDocSourceParams) (GetDocSourceRow, error) {
	row := q.db.QueryRow(ctx, getDocSource, arg.ID, arg.WorkspaceID)
	var i GetDocSourceRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CollectionID,
		&i.Name,
		&i.SourceType,
		&i.Config,
		&i.AccessTokenEncrypted,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDocSourceForSync = `-- name: GetDocSourceForSync :one
SELECT workspace_id, collection_id, source_type, config, access_token_encrypted
FROM doc_sources
WHERE id = $1
`

type GetDocSourceForSyncRow struct {
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
	CollectionID         pgtype.UUID `json:"collection_id"`
	SourceType           string      `json:"source_type"`
	Config               []byte      `json:"config"`
	AccessTokenEncrypted *string     `json:"access_token_encrypted"`
}

func (q *Queries) GetDocSourceForSync(ctx context.Context, id pgtype.UUID) (GetDocSourceForSyncRow, error) {
	row := q.db.QueryRow(ctx, getDocSourceForSync, id)
	var i GetDocSourceForSyncRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.CollectionID,
		&i.SourceType,
		&i.Config,
		&i.AccessTokenEncrypted,
	)
	return i, err
}

const getManualDocLink = `-- name: GetManualDocLink :one
SELECT m.id, m.workspace_doc_id, m.request_id, m.created_at
FROM manual_doc_links m
JOIN workspace_docs d ON d.id = m.workspace_doc_id
WHERE m.id = $1 AND d.workspace_id = $2
`

type GetManualDocLinkParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetManualDocLink(ctx context.Context, arg GetManualDocLinkParams) (ManualDocLink, error) {
	row := q.db.QueryRow(ctx, getManualDocLink, arg.ID, arg.WorkspaceID)
	var i ManualDocLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceDocID,
		&i.RequestID,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceDocByID = `-- name: GetWorkspaceDocByID :one
SELECT id, workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at
FROM workspace_docs
WHERE id = $1 AND workspace_id = $2
`

type GetWorkspaceDocByIDParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetWorkspaceDocByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceDocByID(ctx context.Context, arg GetWorkspaceDocByIDParams) (GetWorkspaceDocByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceDocByID, arg.ID, arg.WorkspaceID)
	var i GetWorkspaceDocByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.ContentMd,
		&i.SourcePath,
		&i.IsLocal,
		&i.LinkedOperationIds,
		&i.LinkedRequestNames,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceDocBySlug = `-- name: GetWorkspaceDocBySlug :one
SELECT id, workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at
FROM workspace_docs
WHERE workspace_id = $1 AND slug = $2
`

type GetWorkspaceDocBySlugParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Slug        string      `json:"slug"`
}

type GetWorkspaceDocBySlugRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceDocBySlug(ctx context.Context, arg GetWorkspaceDocBySlugParams) (GetWorkspaceDocBySlugRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceDocBySlug, arg.WorkspaceID, arg.Slug)
	var i GetWorkspaceDocBySlugRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.ContentMd,
		&i.SourcePath,
		&i.IsLocal,
		&i.LinkedOperationIds,
		&i.LinkedRequestNames,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocSources = `-- name: ListDocSources :many
SELECT id, workspace_id, collection_id, name, source_type, config, access_token_encrypted, last_synced_at, created_at
FROM doc_sources
WHERE workspace_id = $1
ORDER BY name
`

type ListDocSourcesRow struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	Name                 string             `json:"name"`
	SourceType           string             `json:"source_type"`
	Config               []byte             `json:"config"`
	AccessTokenEncrypted *string            `json:"access_token_encrypted"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDocSources(ctx context.Context, workspaceID pgtype.UUID) ([]ListDocSourcesRow, error) {
	rows, err := q.db.Query(ctx, listDocSources, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocSourcesRow{}
	for rows.Next() {
		var i ListDocSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CollectionID,
			&i.Name,
			&i.SourceType,
			&i.Config,
			&i.AccessTokenEncrypted,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDocLinksByDoc = `-- name: ListManualDocLinksByDoc :many
SELECT m.id, m.request_id, r.name, r.method, r.url,
       COALESCE(r.source_operation_id, ''), c.name AS collection_name
FROM manual_doc_links m
JOIN workspace_docs d ON d.id = m.workspace_doc_id
JOIN requests r ON r.id = m.request_id
JOIN collections c ON c.id = r.collection_id
WHERE m.workspace_doc_id = $1 AND d.workspace_id = $2
ORDER BY c.name, r.sort_order, r.name
`

type ListManualDocLinksByDocParams struct {
	WorkspaceDocID pgtype.UUID `json:"workspace_doc_id"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
}

type ListManualDocLinksByDocRow struct {
	ID                pgtype.UUID `json:"id"`
	RequestID         pgtype.UUID `json:"request_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	SourceOperationID string      `json:"source_operation_id"`
	CollectionName    string      `json:"collection_name"`
}

func (q *Queries) ListManualDocLinksByDoc(ctx context.Context, arg ListManualDocLinksByDocParams) ([]ListManualDocLinksByDocRow, error) {
	rows, err := q.db.Query(ctx, listManualDocLinksByDoc, arg.WorkspaceDocID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManualDocLinksByDocRow{}
	for rows.Next() {
		var i ListManualDocLinksByDocRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.SourceOperationID,
			&i.CollectionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDocLinksByWorkspace = `-- name: ListManualDocLinksByWorkspace :many
SELECT m.id, m.workspace_doc_id, m.request_id, d.slug AS doc_slug, r.name AS request_name
FROM manual_doc_links m
JOIN workspace_docs d ON d.id = m.workspace_doc_id
JOIN requests r ON r.id = m.request_id
JOIN collections c ON c.id = r.collection_id
WHERE d.workspace_id = $1
ORDER BY d.slug, r.name
`

type ListManualDocLinksByWorkspaceRow struct {
	ID             pgtype.UUID `json:"id"`
	WorkspaceDocID pgtype.UUID `json:"workspace_doc_id"`
	RequestID      pgtype.UUID `json:"request_id"`
	DocSlug        string      `json:"doc_slug"`
	RequestName    string      `json:"request_name"`
}

func (q *Queries) ListManualDocLinksByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListManualDocLinksByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listManualDocLinksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManualDocLinksByWorkspaceRow{}
	for rows.Next() {
		var i ListManualDocLinksByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceDocID,
			&i.RequestID,
			&i.DocSlug,
			&i.RequestName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualDocLinksForRequest = `-- name: ListManualDocLinksForRequest :many
SELECT m.id AS link_id, d.id, d.slug, d.title, d.content_md, d.source_path, d.is_local, d.linked_operation_ids, d.linked_request_names, d.updated_at
FROM manual_doc_links m
JOIN workspace_docs d ON d.id = m.workspace_doc_id
WHERE m.request_id = $1
ORDER BY d.title
`

type ListManualDocLinksForRequestRow struct {
	LinkID             pgtype.UUID        `json:"link_id"`
	ID                 pgtype.UUID        `json:"id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListManualDocLinksForRequest(ctx context.Context, requestID pgtype.UUID) ([]ListManualDocLinksForRequestRow, error) {
	rows, err := q.db.Query(ctx, listManualDocLinksForRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListManualDocLinksForRequestRow{}
	for rows.Next() {
		var i ListManualDocLinksForRequestRow
		if err := rows.Scan(
			&i.LinkID,
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.ContentMd,
			&i.SourcePath,
			&i.IsLocal,
			&i.LinkedOperationIds,
			&i.LinkedRequestNames,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceDocSummaries = `-- name: ListWorkspaceDocSummaries :many
SELECT id, workspace_id, slug, title, source_path, is_local, updated_at
FROM workspace_docs
WHERE workspace_id = $1
ORDER BY source_path, title
`

type ListWorkspaceDocSummariesRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Slug        string             `json:"slug"`
	Title       string             `json:"title"`
	SourcePath  string             `json:"source_path"`
	IsLocal     bool               `json:"is_local"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkspaceDocSummaries(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceDocSummariesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDocSummaries, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceDocSummariesRow{}
	for rows.Next() {
		var i ListWorkspaceDocSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.SourcePath,
			&i.IsLocal,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceDocs = `-- name: ListWorkspaceDocs :many
SELECT id, workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at
FROM workspace_docs
WHERE workspace_id = $1
ORDER BY source_path, title
`

type ListWorkspaceDocsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkspaceDocs(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceDocsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDocs, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceDocsRow{}
	for rows.Next() {
		var i ListWorkspaceDocsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.ContentMd,
			&i.SourcePath,
			&i.IsLocal,
			&i.LinkedOperationIds,
			&i.LinkedRequestNames,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceDocsByDocSource = `-- name: ListWorkspaceDocsByDocSource :many
SELECT id, workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at
FROM workspace_docs
WHERE workspace_id = $1 AND doc_source_id = $2
ORDER BY source_path, title
`

type ListWorkspaceDocsByDocSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DocSourceID pgtype.UUID `json:"doc_source_id"`
}

type ListWorkspaceDocsByDocSourceRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkspaceDocsByDocSource(ctx context.Context, arg ListWorkspaceDocsByDocSourceParams) ([]ListWorkspaceDocsByDocSourceRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDocsByDocSource, arg.WorkspaceID, arg.DocSourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceDocsByDocSourceRow{}
	for rows.Next() {
		var i ListWorkspaceDocsByDocSourceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.ContentMd,
			&i.SourcePath,
			&i.IsLocal,
			&i.LinkedOperationIds,
			&i.LinkedRequestNames,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceDocsByOperation = `-- name: ListWorkspaceDocsByOperation :many
SELECT id, workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at
FROM workspace_docs
WHERE workspace_id = $1
  AND $2::text = ANY(linked_operation_ids)
ORDER BY source_path, title
`

type ListWorkspaceDocsByOperationParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	OperationID string      `json:"operation_id"`
}

type ListWorkspaceDocsByOperationRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkspaceDocsByOperation(ctx context.Context, arg ListWorkspaceDocsByOperationParams) ([]ListWorkspaceDocsByOperationRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDocsByOperation, arg.WorkspaceID, arg.OperationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceDocsByOperationRow{}
	for rows.Next() {
		var i ListWorkspaceDocsByOperationRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.ContentMd,
			&i.SourcePath,
			&i.IsLocal,
			&i.LinkedOperationIds,
			&i.LinkedRequestNames,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceDocsByOperationIDs = `-- name: ListWorkspaceDocsByOperationIDs :many
SELECT id, workspace_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at
FROM workspace_docs
WHERE workspace_id = $1
  AND linked_operation_ids && $2::text[]
ORDER BY source_path, title
`

type ListWorkspaceDocsByOperationIDsParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	OperationIds []string    `json:"operation_ids"`
}

type ListWorkspaceDocsByOperationIDsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	LinkedRequestNames []string           `json:"linked_request_names"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListWorkspaceDocsByOperationIDs(ctx context.Context, arg ListWorkspaceDocsByOperationIDsParams) ([]ListWorkspaceDocsByOperationIDsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceDocsByOperationIDs, arg.WorkspaceID, arg.OperationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceDocsByOperationIDsRow{}
	for rows.Next() {
		var i ListWorkspaceDocsByOperationIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.ContentMd,
			&i.SourcePath,
			&i.IsLocal,
			&i.LinkedOperationIds,
			&i.LinkedRequestNames,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocSource = `-- name: UpdateDocSource :exec
UPDATE doc_sources
SET name = COALESCE($1, name),
    collection_id = CASE WHEN $2::boolean THEN $3 ELSE collection_id END,
    config = COALESCE($4, config),
    access_token_encrypted = COALESCE($5, access_token_encrypted)
WHERE id = $6 AND workspace_id = $7
`

type UpdateDocSourceParams struct {
	Name                 *string     `json:"name"`
	SetCollectionID      bool        `json:"set_collection_id"`
	CollectionID         pgtype.UUID `json:"collection_id"`
	Config               []byte      `json:"config"`
	AccessTokenEncrypted *string     `json:"access_token_encrypted"`
	ID                   pgtype.UUID `json:"id"`
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateDocSource(ctx context.Context, arg UpdateDocSourceParams) error {
	_, err := q.db.Exec(ctx, updateDocSource,
		arg.Name,
		arg.SetCollectionID,
		arg.CollectionID,
		arg.Config,
		arg.AccessTokenEncrypted,
		arg.ID,
		arg.WorkspaceID,
	)
	return err
}

const updateDocSourceLastSynced = `-- name: UpdateDocSourceLastSynced :exec
UPDATE doc_sources
SET last_synced_at = now()
WHERE id = $1
`

func (q *Queries) UpdateDocSourceLastSynced(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDocSourceLastSynced, id)
	return err
}

const updateWorkspaceDoc = `-- name: UpdateWorkspaceDoc :exec
UPDATE workspace_docs
SET title = $1,
    content_md = $2,
    linked_operation_ids = $3,
    linked_request_names = $4,
    updated_at = now()
WHERE workspace_id = $5 AND slug = $6
`

type UpdateWorkspaceDocParams struct {
	Title              string      `json:"title"`
	ContentMd          string      `json:"content_md"`
	LinkedOperationIds []string    `json:"linked_operation_ids"`
	LinkedRequestNames []string    `json:"linked_request_names"`
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	Slug               string      `json:"slug"`
}

func (q *Queries) UpdateWorkspaceDoc(ctx context.Context, arg UpdateWorkspaceDocParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceDoc,
		arg.Title,
		arg.ContentMd,
		arg.LinkedOperationIds,
		arg.LinkedRequestNames,
		arg.WorkspaceID,
		arg.Slug,
	)
	return err
}

const upsertWorkspaceDoc = `-- name: UpsertWorkspaceDoc :exec
INSERT INTO workspace_docs (workspace_id, doc_source_id, slug, title, content_md, source_path, is_local, linked_operation_ids, linked_request_names, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now())
ON CONFLICT (workspace_id, source_path) WHERE source_path <> '' DO UPDATE SET
    slug = EXCLUDED.slug,
    title = EXCLUDED.title,
    content_md = EXCLUDED.content_md,
    linked_operation_ids = EXCLUDED.linked_operation_ids,
    linked_request_names = EXCLUDED.linked_request_names,
    updated_at = now(),
    doc_source_id = EXCLUDED.doc_source_id,
    is_local = EXCLUDED.is_local
`

type UpsertWorkspaceDocParams struct {
	WorkspaceID        pgtype.UUID `json:"workspace_id"`
	DocSourceID        pgtype.UUID `json:"doc_source_id"`
	Slug               string      `json:"slug"`
	Title              string      `json:"title"`
	ContentMd          string      `json:"content_md"`
	SourcePath         string      `json:"source_path"`
	IsLocal            bool        `json:"is_local"`
	LinkedOperationIds []string    `json:"linked_operation_ids"`
	LinkedRequestNames []string    `json:"linked_request_names"`
}

func (q *Queries) UpsertWorkspaceDoc(ctx context.Context, arg UpsertWorkspaceDocParams) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceDoc,
		arg.WorkspaceID,
		arg.DocSourceID,
		arg.Slug,
		arg.Title,
		arg.ContentMd,
		arg.SourcePath,
		arg.IsLocal,
		arg.LinkedOperationIds,
		arg.LinkedRequestNames,
	)
	return err
}

const verifyRequestInWorkspace = `-- name: VerifyRequestInWorkspace :one
SELECT r.id
FROM requests r
JOIN collections c ON c.id = r.collection_id
WHERE r.id = $1 AND c.workspace_id = $2
`

type VerifyRequestInWorkspaceParams struct {
	RequestID   pgtype.UUID `json:"request_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) VerifyRequestInWorkspace(ctx context.Context, arg VerifyRequestInWorkspaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, verifyRequestInWorkspace, arg.RequestID, arg.WorkspaceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
