// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (workspace_id, name, stage, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateEnvironmentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Stage       string      `json:"stage"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.WorkspaceID,
		arg.Name,
		arg.Stage,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments
WHERE id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const deleteEnvironmentVariables = `-- name: DeleteEnvironmentVariables :exec
DELETE FROM environment_variables
WHERE environment_id = $1
`

func (q *Queries) DeleteEnvironmentVariables(ctx context.Context, environmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentVariables, environmentID)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, workspace_id, name, stage
FROM environments
WHERE id = $1
`

type GetEnvironmentRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Stage       string      `json:"stage"`
}

func (q *Queries) GetEnvironment(ctx context.Context, id pgtype.UUID) (GetEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i GetEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Stage,
	)
	return i, err
}

const listEnvironmentVariables = `-- name: ListEnvironmentVariables :many
SELECT id, key, value_encrypted, is_secret, phase, enabled, type, description, expr
FROM environment_variables
WHERE environment_id = $1
ORDER BY phase, key
`

type ListEnvironmentVariablesRow struct {
	ID             pgtype.UUID `json:"id"`
	Key            string      `json:"key"`
	ValueEncrypted string      `json:"value_encrypted"`
	IsSecret       bool        `json:"is_secret"`
	Phase          string      `json:"phase"`
	Enabled        bool        `json:"enabled"`
	Type           string      `json:"type"`
	Description    string      `json:"description"`
	Expr           string      `json:"expr"`
}

func (q *Queries) ListEnvironmentVariables(ctx context.Context, environmentID pgtype.UUID) ([]ListEnvironmentVariablesRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentVariables, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentVariablesRow{}
	for rows.Next() {
		var i ListEnvironmentVariablesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.ValueEncrypted,
			&i.IsSecret,
			&i.Phase,
			&i.Enabled,
			&i.Type,
			&i.Description,
			&i.Expr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentVariablesForDecrypt = `-- name: ListEnvironmentVariablesForDecrypt :many
SELECT key, value_encrypted, is_secret, phase, enabled, expr
FROM environment_variables
WHERE environment_id = $1
`

type ListEnvironmentVariablesForDecryptRow struct {
	Key            string `json:"key"`
	ValueEncrypted string `json:"value_encrypted"`
	IsSecret       bool   `json:"is_secret"`
	Phase          string `json:"phase"`
	Enabled        bool   `json:"enabled"`
	Expr           string `json:"expr"`
}

func (q *Queries) ListEnvironmentVariablesForDecrypt(ctx context.Context, environmentID pgtype.UUID) ([]ListEnvironmentVariablesForDecryptRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentVariablesForDecrypt, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentVariablesForDecryptRow{}
	for rows.Next() {
		var i ListEnvironmentVariablesForDecryptRow
		if err := rows.Scan(
			&i.Key,
			&i.ValueEncrypted,
			&i.IsSecret,
			&i.Phase,
			&i.Enabled,
			&i.Expr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, workspace_id, name, stage
FROM environments
WHERE workspace_id = $1
ORDER BY name
`

type ListEnvironmentsRow struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Stage       string      `json:"stage"`
}

func (q *Queries) ListEnvironments(ctx context.Context, workspaceID pgtype.UUID) ([]ListEnvironmentsRow, error) {
	rows, err := q.db.Query(ctx, listEnvironments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentsRow{}
	for rows.Next() {
		var i ListEnvironmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentName = `-- name: UpdateEnvironmentName :exec
UPDATE environments
SET name = $1, updated_at = now()
WHERE id = $2
`

type UpdateEnvironmentNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateEnvironmentName(ctx context.Context, arg UpdateEnvironmentNameParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentName, arg.Name, arg.ID)
	return err
}

const updateEnvironmentStage = `-- name: UpdateEnvironmentStage :exec
UPDATE environments
SET stage = $1, updated_at = now()
WHERE id = $2
`

type UpdateEnvironmentStageParams struct {
	Stage string      `json:"stage"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateEnvironmentStage(ctx context.Context, arg UpdateEnvironmentStageParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentStage, arg.Stage, arg.ID)
	return err
}

const upsertEnvironmentVariable = `-- name: UpsertEnvironmentVariable :exec
INSERT INTO environment_variables (environment_id, key, value_encrypted, is_secret, phase, enabled, type, description, expr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (environment_id, key, phase) DO UPDATE SET
    value_encrypted = EXCLUDED.value_encrypted,
    is_secret = EXCLUDED.is_secret,
    enabled = EXCLUDED.enabled,
    type = EXCLUDED.type,
    description = EXCLUDED.description,
    expr = EXCLUDED.expr,
    updated_at = now()
`

type UpsertEnvironmentVariableParams struct {
	EnvironmentID  pgtype.UUID `json:"environment_id"`
	Key            string      `json:"key"`
	ValueEncrypted string      `json:"value_encrypted"`
	IsSecret       bool        `json:"is_secret"`
	Phase          string      `json:"phase"`
	Enabled        bool        `json:"enabled"`
	Type           string      `json:"type"`
	Description    string      `json:"description"`
	Expr           string      `json:"expr"`
}

func (q *Queries) UpsertEnvironmentVariable(ctx context.Context, arg UpsertEnvironmentVariableParams) error {
	_, err := q.db.Exec(ctx, upsertEnvironmentVariable,
		arg.EnvironmentID,
		arg.Key,
		arg.ValueEncrypted,
		arg.IsSecret,
		arg.Phase,
		arg.Enabled,
		arg.Type,
		arg.Description,
		arg.Expr,
	)
	return err
}
