// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitbranches.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGitBranchCache = `-- name: GetGitBranchCache :one
SELECT branches, fetched_at
FROM git_branch_cache
WHERE workspace_id = $1 AND repo_key = $2
`

type GetGitBranchCacheParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RepoKey     string      `json:"repo_key"`
}

type GetGitBranchCacheRow struct {
	Branches  []byte             `json:"branches"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetGitBranchCache(ctx context.Context, arg GetGitBranchCacheParams) (GetGitBranchCacheRow, error) {
	row := q.db.QueryRow(ctx, getGitBranchCache, arg.WorkspaceID, arg.RepoKey)
	var i GetGitBranchCacheRow
	err := row.Scan(&i.Branches, &i.FetchedAt)
	return i, err
}

const upsertGitBranchCache = `-- name: UpsertGitBranchCache :exec
INSERT INTO git_branch_cache (workspace_id, repo_key, branches, fetched_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (workspace_id, repo_key)
DO UPDATE SET branches = EXCLUDED.branches, fetched_at = now()
`

type UpsertGitBranchCacheParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RepoKey     string      `json:"repo_key"`
	Branches    []byte      `json:"branches"`
}

func (q *Queries) UpsertGitBranchCache(ctx context.Context, arg UpsertGitBranchCacheParams) error {
	_, err := q.db.Exec(ctx, upsertGitBranchCache, arg.WorkspaceID, arg.RepoKey, arg.Branches)
	return err
}
