// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHistoryForShareSnapshot = `-- name: GetHistoryForShareSnapshot :one
SELECT h.snapshot, h.response, h.test_results, h.duration_ms, h.status_code, h.executed_at,
       h.executed_by, u.display_name, u.email
FROM history h
JOIN users u ON u.id = h.executed_by
WHERE h.id = $1 AND h.workspace_id = $2
`

type GetHistoryForShareSnapshotParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetHistoryForShareSnapshotRow struct {
	Snapshot    []byte             `json:"snapshot"`
	Response    []byte             `json:"response"`
	TestResults []byte             `json:"test_results"`
	DurationMs  int64              `json:"duration_ms"`
	StatusCode  int32              `json:"status_code"`
	ExecutedAt  pgtype.Timestamptz `json:"executed_at"`
	ExecutedBy  pgtype.UUID        `json:"executed_by"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
}

func (q *Queries) GetHistoryForShareSnapshot(ctx context.Context, arg GetHistoryForShareSnapshotParams) (GetHistoryForShareSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getHistoryForShareSnapshot, arg.ID, arg.WorkspaceID)
	var i GetHistoryForShareSnapshotRow
	err := row.Scan(
		&i.Snapshot,
		&i.Response,
		&i.TestResults,
		&i.DurationMs,
		&i.StatusCode,
		&i.ExecutedAt,
		&i.ExecutedBy,
		&i.DisplayName,
		&i.Email,
	)
	return i, err
}

const listHistoryByWorkspace = `-- name: ListHistoryByWorkspace :many
SELECT h.id, h.workspace_id, h.request_id, h.snapshot, h.response, h.test_results,
       h.executed_by, u.display_name, u.email, h.executed_at, h.duration_ms, h.status_code
FROM history h
JOIN users u ON u.id = h.executed_by
WHERE h.workspace_id = $1
ORDER BY h.executed_at DESC
LIMIT 100
`

type ListHistoryByWorkspaceRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	RequestID   pgtype.UUID        `json:"request_id"`
	Snapshot    []byte             `json:"snapshot"`
	Response    []byte             `json:"response"`
	TestResults []byte             `json:"test_results"`
	ExecutedBy  pgtype.UUID        `json:"executed_by"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	ExecutedAt  pgtype.Timestamptz `json:"executed_at"`
	DurationMs  int64              `json:"duration_ms"`
	StatusCode  int32              `json:"status_code"`
}

func (q *Queries) ListHistoryByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListHistoryByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listHistoryByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryByWorkspaceRow{}
	for rows.Next() {
		var i ListHistoryByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RequestID,
			&i.Snapshot,
			&i.Response,
			&i.TestResults,
			&i.ExecutedBy,
			&i.DisplayName,
			&i.Email,
			&i.ExecutedAt,
			&i.DurationMs,
			&i.StatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHistoryByWorkspaceAndRequest = `-- name: ListHistoryByWorkspaceAndRequest :many
SELECT h.id, h.workspace_id, h.request_id, h.snapshot, h.response, h.test_results,
       h.executed_by, u.display_name, u.email, h.executed_at, h.duration_ms, h.status_code
FROM history h
JOIN users u ON u.id = h.executed_by
WHERE h.workspace_id = $1
  AND h.request_id = $2
ORDER BY h.executed_at DESC
LIMIT 100
`

type ListHistoryByWorkspaceAndRequestParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RequestID   pgtype.UUID `json:"request_id"`
}

type ListHistoryByWorkspaceAndRequestRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	RequestID   pgtype.UUID        `json:"request_id"`
	Snapshot    []byte             `json:"snapshot"`
	Response    []byte             `json:"response"`
	TestResults []byte             `json:"test_results"`
	ExecutedBy  pgtype.UUID        `json:"executed_by"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	ExecutedAt  pgtype.Timestamptz `json:"executed_at"`
	DurationMs  int64              `json:"duration_ms"`
	StatusCode  int32              `json:"status_code"`
}

func (q *Queries) ListHistoryByWorkspaceAndRequest(ctx context.Context, arg ListHistoryByWorkspaceAndRequestParams) ([]ListHistoryByWorkspaceAndRequestRow, error) {
	rows, err := q.db.Query(ctx, listHistoryByWorkspaceAndRequest, arg.WorkspaceID, arg.RequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHistoryByWorkspaceAndRequestRow{}
	for rows.Next() {
		var i ListHistoryByWorkspaceAndRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RequestID,
			&i.Snapshot,
			&i.Response,
			&i.TestResults,
			&i.ExecutedBy,
			&i.DisplayName,
			&i.Email,
			&i.ExecutedAt,
			&i.DurationMs,
			&i.StatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
