// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importexport.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertImportedCollection = `-- name: InsertImportedCollection :one
INSERT INTO collections (workspace_id, parent_id, name, description, sort_order, variables, headers, auth, pre_request_script, test_script, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type InsertImportedCollectionParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ParentID         pgtype.UUID `json:"parent_id"`
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	SortOrder        int32       `json:"sort_order"`
	Variables        []byte      `json:"variables"`
	Headers          []byte      `json:"headers"`
	Auth             []byte      `json:"auth"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertImportedCollection(ctx context.Context, arg InsertImportedCollectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertImportedCollection,
		arg.WorkspaceID,
		arg.ParentID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.Variables,
		arg.Headers,
		arg.Auth,
		arg.PreRequestScript,
		arg.TestScript,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
