// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkspaceInvite = `-- name: DeleteWorkspaceInvite :exec
DELETE FROM workspace_invites
WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkspaceInviteParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteWorkspaceInvite(ctx context.Context, arg DeleteWorkspaceInviteParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceInvite, arg.ID, arg.WorkspaceID)
	return err
}

const getWorkspaceInviteByToken = `-- name: GetWorkspaceInviteByToken :one
SELECT id, workspace_id, email, role::text, expires_at, accepted_at
FROM workspace_invites
WHERE token = $1
`

type GetWorkspaceInviteByTokenRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
}

func (q *Queries) GetWorkspaceInviteByToken(ctx context.Context, token string) (GetWorkspaceInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInviteByToken, token)
	var i GetWorkspaceInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listPendingWorkspaceInvites = `-- name: ListPendingWorkspaceInvites :many
SELECT id, workspace_id, email, role::text, expires_at, created_at
FROM workspace_invites
WHERE workspace_id = $1
  AND accepted_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

type ListPendingWorkspaceInvitesRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        string             `json:"role"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingWorkspaceInvites(ctx context.Context, workspaceID pgtype.UUID) ([]ListPendingWorkspaceInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPendingWorkspaceInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingWorkspaceInvitesRow{}
	for rows.Next() {
		var i ListPendingWorkspaceInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspaceInviteAccepted = `-- name: MarkWorkspaceInviteAccepted :exec
UPDATE workspace_invites
SET accepted_at = now()
WHERE id = $1
`

func (q *Queries) MarkWorkspaceInviteAccepted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markWorkspaceInviteAccepted, id)
	return err
}

const upsertWorkspaceInvite = `-- name: UpsertWorkspaceInvite :one
INSERT INTO workspace_invites (workspace_id, email, role, token, expires_at, created_by)
VALUES ($1, $2, $3::workspace_role, $4, $5, $6)
ON CONFLICT (workspace_id, email) DO UPDATE SET
    role = EXCLUDED.role,
    token = EXCLUDED.token,
    expires_at = EXCLUDED.expires_at,
    created_by = EXCLUDED.created_by,
    accepted_at = NULL
RETURNING id
`

type UpsertWorkspaceInviteParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        WorkspaceRole      `json:"role"`
	Token       string             `json:"token"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) UpsertWorkspaceInvite(ctx context.Context, arg UpsertWorkspaceInviteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceInvite,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
