// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ShareKind string

const (
	ShareKindRequest ShareKind = "request"
	ShareKindHistory ShareKind = "history"
	ShareKindCatalog ShareKind = "catalog"
)

func (e *ShareKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShareKind(s)
	case string:
		*e = ShareKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ShareKind: %T", src)
	}
	return nil
}

type NullShareKind struct {
	ShareKind ShareKind `json:"share_kind"`
	Valid     bool      `json:"valid"` // Valid is true if ShareKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShareKind) Scan(value interface{}) error {
	if value == nil {
		ns.ShareKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShareKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShareKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShareKind), nil
}

type WorkspaceRole string

const (
	WorkspaceRoleOwner  WorkspaceRole = "owner"
	WorkspaceRoleEditor WorkspaceRole = "editor"
	WorkspaceRoleViewer WorkspaceRole = "viewer"
)

func (e *WorkspaceRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceRole(s)
	case string:
		*e = WorkspaceRole(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceRole: %T", src)
	}
	return nil
}

type NullWorkspaceRole struct {
	WorkspaceRole WorkspaceRole `json:"workspace_role"`
	Valid         bool          `json:"valid"` // Valid is true if WorkspaceRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceRole) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceRole), nil
}

type ActivityLog struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ApiSpec struct {
	ID           pgtype.UUID        `json:"id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	CollectionID pgtype.UUID        `json:"collection_id"`
	Name         string             `json:"name"`
	SourceType   string             `json:"source_type"`
	SpecUrl      string             `json:"spec_url"`
	SpecHash     string             `json:"spec_hash"`
	SpecContent  []byte             `json:"spec_content"`
	BaseUrlVar   string             `json:"base_url_var"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ApiSpecEnvironmentUrl struct {
	ApiSpecID     pgtype.UUID `json:"api_spec_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	BaseUrl       string      `json:"base_url"`
}

type BrunoSource struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	Name                 string             `json:"name"`
	Config               []byte             `json:"config"`
	AccessTokenEncrypted *string            `json:"access_token_encrypted"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Collection struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	ParentID           pgtype.UUID        `json:"parent_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	SortOrder          int32              `json:"sort_order"`
	Variables          []byte             `json:"variables"`
	Headers            []byte             `json:"headers"`
	Auth               []byte             `json:"auth"`
	Presets            []byte             `json:"presets"`
	Proxy              []byte             `json:"proxy"`
	ClientCertificates []byte             `json:"client_certificates"`
	Secrets            []byte             `json:"secrets"`
	PreRequestScript   string             `json:"pre_request_script"`
	TestScript         string             `json:"test_script"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SourcePath         string             `json:"source_path"`
	BrunoSourceID      pgtype.UUID        `json:"bruno_source_id"`
}

type DocLinkSuggestion struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	WorkspaceDocID pgtype.UUID        `json:"workspace_doc_id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	Reason         string             `json:"reason"`
	Confidence     string             `json:"confidence"`
	Evidence       []byte             `json:"evidence"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
}

type DocSource struct {
	ID                   pgtype.UUID        `json:"id"`
	WorkspaceID          pgtype.UUID        `json:"workspace_id"`
	CollectionID         pgtype.UUID        `json:"collection_id"`
	Name                 string             `json:"name"`
	SourceType           string             `json:"source_type"`
	Config               []byte             `json:"config"`
	AccessTokenEncrypted *string            `json:"access_token_encrypted"`
	LastSyncedAt         pgtype.Timestamptz `json:"last_synced_at"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Environment struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	Stage       string             `json:"stage"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EnvironmentVariable struct {
	ID             pgtype.UUID        `json:"id"`
	EnvironmentID  pgtype.UUID        `json:"environment_id"`
	Key            string             `json:"key"`
	ValueEncrypted string             `json:"value_encrypted"`
	IsSecret       bool               `json:"is_secret"`
	Phase          string             `json:"phase"`
	Enabled        bool               `json:"enabled"`
	Type           string             `json:"type"`
	Description    string             `json:"description"`
	Expr           string             `json:"expr"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Example struct {
	ID        pgtype.UUID        `json:"id"`
	RequestID pgtype.UUID        `json:"request_id"`
	Name      string             `json:"name"`
	Response  []byte             `json:"response"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type History struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	RequestID   pgtype.UUID        `json:"request_id"`
	Snapshot    []byte             `json:"snapshot"`
	Response    []byte             `json:"response"`
	TestResults []byte             `json:"test_results"`
	ExecutedBy  pgtype.UUID        `json:"executed_by"`
	ExecutedAt  pgtype.Timestamptz `json:"executed_at"`
	DurationMs  int64              `json:"duration_ms"`
	StatusCode  int32              `json:"status_code"`
}

type ManualDocLink struct {
	ID             pgtype.UUID        `json:"id"`
	WorkspaceDocID pgtype.UUID        `json:"workspace_doc_id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Request struct {
	ID                pgtype.UUID        `json:"id"`
	CollectionID      pgtype.UUID        `json:"collection_id"`
	Name              string             `json:"name"`
	Method            string             `json:"method"`
	Url               string             `json:"url"`
	Headers           []byte             `json:"headers"`
	Params            []byte             `json:"params"`
	PathVars          []byte             `json:"path_vars"`
	Body              []byte             `json:"body"`
	Auth              []byte             `json:"auth"`
	Settings          []byte             `json:"settings"`
	PreRequestScript  string             `json:"pre_request_script"`
	TestScript        string             `json:"test_script"`
	SortOrder         int32              `json:"sort_order"`
	Description       string             `json:"description"`
	TemplateID        pgtype.UUID        `json:"template_id"`
	IsTemplate        bool               `json:"is_template"`
	OverriddenFields  []string           `json:"overridden_fields"`
	SourceSpecID      pgtype.UUID        `json:"source_spec_id"`
	SourceOperationID string             `json:"source_operation_id"`
	SourceOpHash      string             `json:"source_op_hash"`
	ApiDoc            []byte             `json:"api_doc"`
	DocsOverridden    bool               `json:"docs_overridden"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SourcePath        string             `json:"source_path"`
	BrunoSourceID     pgtype.UUID        `json:"bruno_source_id"`
}

type Share struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Kind        ShareKind          `json:"kind"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Token       string             `json:"token"`
	Title       string             `json:"title"`
	Snapshot    []byte             `json:"snapshot"`
	Visibility  string             `json:"visibility"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	AuthProvider string             `json:"auth_provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Variables   []byte             `json:"variables"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []string           `json:"scopes"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceDoc struct {
	ID                 pgtype.UUID        `json:"id"`
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	DocSourceID        pgtype.UUID        `json:"doc_source_id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	ContentMd          string             `json:"content_md"`
	SourcePath         string             `json:"source_path"`
	IsLocal            bool               `json:"is_local"`
	LinkedOperationIds []string           `json:"linked_operation_ids"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceInvite struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Email       string             `json:"email"`
	Role        WorkspaceRole      `json:"role"`
	Token       string             `json:"token"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        WorkspaceRole      `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
