// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const backfillRequestOperationIDs = `-- name: BackfillRequestOperationIDs :execrows
UPDATE requests r
SET source_operation_id = $1,
    updated_at = now()
FROM collections c
WHERE r.collection_id = c.id
  AND c.workspace_id = $2
  AND r.id = $3
  AND r.source_operation_id = ''
  AND r.source_spec_id IS NULL
`

type BackfillRequestOperationIDsParams struct {
	SourceOperationID string      `json:"source_operation_id"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	RequestID         pgtype.UUID `json:"request_id"`
}

func (q *Queries) BackfillRequestOperationIDs(ctx context.Context, arg BackfillRequestOperationIDsParams) (int64, error) {
	result, err := q.db.Exec(ctx, backfillRequestOperationIDs, arg.SourceOperationID, arg.WorkspaceID, arg.RequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createExample = `-- name: CreateExample :one
INSERT INTO examples (request_id, name, response, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateExampleParams struct {
	RequestID pgtype.UUID `json:"request_id"`
	Name      string      `json:"name"`
	Response  []byte      `json:"response"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createExample,
		arg.RequestID,
		arg.Name,
		arg.Response,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createHistoryEntry = `-- name: CreateHistoryEntry :one
INSERT INTO history (
    workspace_id, request_id, snapshot, response, test_results,
    executed_by, duration_ms, status_code
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
) RETURNING id
`

type CreateHistoryEntryParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RequestID   pgtype.UUID `json:"request_id"`
	Snapshot    []byte      `json:"snapshot"`
	Response    []byte      `json:"response"`
	TestResults []byte      `json:"test_results"`
	ExecutedBy  pgtype.UUID `json:"executed_by"`
	DurationMs  int64       `json:"duration_ms"`
	StatusCode  int32       `json:"status_code"`
}

func (q *Queries) CreateHistoryEntry(ctx context.Context, arg CreateHistoryEntryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createHistoryEntry,
		arg.WorkspaceID,
		arg.RequestID,
		arg.Snapshot,
		arg.Response,
		arg.TestResults,
		arg.ExecutedBy,
		arg.DurationMs,
		arg.StatusCode,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (
    collection_id, name, method, url, headers, params, path_vars, body, auth, settings,
    pre_request_script, test_script, sort_order, description, template_id, is_template, overridden_fields,
    source_spec_id, source_operation_id, source_op_hash, api_doc, docs_overridden, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23
) RETURNING id
`

type CreateRequestParams struct {
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	Settings          []byte      `json:"settings"`
	PreRequestScript  string      `json:"pre_request_script"`
	TestScript        string      `json:"test_script"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	TemplateID        pgtype.UUID `json:"template_id"`
	IsTemplate        bool        `json:"is_template"`
	OverriddenFields  []string    `json:"overridden_fields"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	ApiDoc            []byte      `json:"api_doc"`
	DocsOverridden    bool        `json:"docs_overridden"`
	CreatedBy         pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SortOrder,
		arg.Description,
		arg.TemplateID,
		arg.IsTemplate,
		arg.OverriddenFields,
		arg.SourceSpecID,
		arg.SourceOperationID,
		arg.SourceOpHash,
		arg.ApiDoc,
		arg.DocsOverridden,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSharedResponseExample = `-- name: CreateSharedResponseExample :exec
INSERT INTO examples (request_id, name, response, created_by)
VALUES ($1, $2, $3, $4)
`

type CreateSharedResponseExampleParams struct {
	RequestID pgtype.UUID `json:"request_id"`
	Name      string      `json:"name"`
	Response  []byte      `json:"response"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateSharedResponseExample(ctx context.Context, arg CreateSharedResponseExampleParams) error {
	_, err := q.db.Exec(ctx, createSharedResponseExample,
		arg.RequestID,
		arg.Name,
		arg.Response,
		arg.CreatedBy,
	)
	return err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests
WHERE id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const duplicateRequest = `-- name: DuplicateRequest :exec
INSERT INTO requests (
    collection_id, name, method, url, headers, params, path_vars, body, auth, settings,
    pre_request_script, test_script, sort_order, description, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
`

type DuplicateRequestParams struct {
	CollectionID     pgtype.UUID `json:"collection_id"`
	Name             string      `json:"name"`
	Method           string      `json:"method"`
	Url              string      `json:"url"`
	Headers          []byte      `json:"headers"`
	Params           []byte      `json:"params"`
	PathVars         []byte      `json:"path_vars"`
	Body             []byte      `json:"body"`
	Auth             []byte      `json:"auth"`
	Settings         []byte      `json:"settings"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	SortOrder        int32       `json:"sort_order"`
	Description      string      `json:"description"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) DuplicateRequest(ctx context.Context, arg DuplicateRequestParams) error {
	_, err := q.db.Exec(ctx, duplicateRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SortOrder,
		arg.Description,
		arg.CreatedBy,
	)
	return err
}

const getRequest = `-- name: GetRequest :one
SELECT id, collection_id, name, method, url, headers, params, path_vars, body, auth, settings,
       pre_request_script, test_script, sort_order, description, template_id, is_template,
       COALESCE(overridden_fields, '{}'), source_spec_id,
       COALESCE(source_operation_id, ''), COALESCE(source_op_hash, ''),
       COALESCE(api_doc, '{}'), docs_overridden
FROM requests
WHERE id = $1
`

type GetRequestRow struct {
	ID                pgtype.UUID `json:"id"`
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	Settings          []byte      `json:"settings"`
	PreRequestScript  string      `json:"pre_request_script"`
	TestScript        string      `json:"test_script"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	TemplateID        pgtype.UUID `json:"template_id"`
	IsTemplate        bool        `json:"is_template"`
	OverriddenFields  []string    `json:"overridden_fields"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	ApiDoc            []byte      `json:"api_doc"`
	DocsOverridden    bool        `json:"docs_overridden"`
}

func (q *Queries) GetRequest(ctx context.Context, id pgtype.UUID) (GetRequestRow, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i GetRequestRow
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Params,
		&i.PathVars,
		&i.Body,
		&i.Auth,
		&i.Settings,
		&i.PreRequestScript,
		&i.TestScript,
		&i.SortOrder,
		&i.Description,
		&i.TemplateID,
		&i.IsTemplate,
		&i.OverriddenFields,
		&i.SourceSpecID,
		&i.SourceOperationID,
		&i.SourceOpHash,
		&i.ApiDoc,
		&i.DocsOverridden,
	)
	return i, err
}

const getRequestDocsBundle = `-- name: GetRequestDocsBundle :one
SELECT r.description, COALESCE(r.api_doc, '{}'), COALESCE(r.source_operation_id, ''), r.collection_id,
       r.method, r.url
FROM requests r
WHERE r.id = $1
`

type GetRequestDocsBundleRow struct {
	Description       string      `json:"description"`
	ApiDoc            []byte      `json:"api_doc"`
	SourceOperationID string      `json:"source_operation_id"`
	CollectionID      pgtype.UUID `json:"collection_id"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
}

func (q *Queries) GetRequestDocsBundle(ctx context.Context, id pgtype.UUID) (GetRequestDocsBundleRow, error) {
	row := q.db.QueryRow(ctx, getRequestDocsBundle, id)
	var i GetRequestDocsBundleRow
	err := row.Scan(
		&i.Description,
		&i.ApiDoc,
		&i.SourceOperationID,
		&i.CollectionID,
		&i.Method,
		&i.Url,
	)
	return i, err
}

const getRequestForShareSnapshot = `-- name: GetRequestForShareSnapshot :one
SELECT r.id, r.collection_id, r.name, r.method, r.url, r.headers, r.params, r.path_vars, r.body, r.auth, r.settings,
       r.pre_request_script, r.test_script, r.sort_order, r.description
FROM requests r
JOIN collections c ON c.id = r.collection_id
WHERE r.id = $1 AND c.workspace_id = $2
`

type GetRequestForShareSnapshotParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetRequestForShareSnapshotRow struct {
	ID               pgtype.UUID `json:"id"`
	CollectionID     pgtype.UUID `json:"collection_id"`
	Name             string      `json:"name"`
	Method           string      `json:"method"`
	Url              string      `json:"url"`
	Headers          []byte      `json:"headers"`
	Params           []byte      `json:"params"`
	PathVars         []byte      `json:"path_vars"`
	Body             []byte      `json:"body"`
	Auth             []byte      `json:"auth"`
	Settings         []byte      `json:"settings"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	SortOrder        int32       `json:"sort_order"`
	Description      string      `json:"description"`
}

func (q *Queries) GetRequestForShareSnapshot(ctx context.Context, arg GetRequestForShareSnapshotParams) (GetRequestForShareSnapshotRow, error) {
	row := q.db.QueryRow(ctx, getRequestForShareSnapshot, arg.ID, arg.WorkspaceID)
	var i GetRequestForShareSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.Params,
		&i.PathVars,
		&i.Body,
		&i.Auth,
		&i.Settings,
		&i.PreRequestScript,
		&i.TestScript,
		&i.SortOrder,
		&i.Description,
	)
	return i, err
}

const getSpecBaseURLForEnvironment = `-- name: GetSpecBaseURLForEnvironment :one
SELECT s.base_url_var, u.base_url
FROM api_specs s
JOIN api_spec_environment_urls u ON u.api_spec_id = s.id AND u.environment_id = $1
WHERE s.id = $2
`

type GetSpecBaseURLForEnvironmentParams struct {
	EnvironmentID pgtype.UUID `json:"environment_id"`
	SpecID        pgtype.UUID `json:"spec_id"`
}

type GetSpecBaseURLForEnvironmentRow struct {
	BaseUrlVar string `json:"base_url_var"`
	BaseUrl    string `json:"base_url"`
}

func (q *Queries) GetSpecBaseURLForEnvironment(ctx context.Context, arg GetSpecBaseURLForEnvironmentParams) (GetSpecBaseURLForEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getSpecBaseURLForEnvironment, arg.EnvironmentID, arg.SpecID)
	var i GetSpecBaseURLForEnvironmentRow
	err := row.Scan(&i.BaseUrlVar, &i.BaseUrl)
	return i, err
}

const getWorkspaceVariables = `-- name: GetWorkspaceVariables :one
SELECT variables
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceVariables(ctx context.Context, id pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorkspaceVariables, id)
	var variables []byte
	err := row.Scan(&variables)
	return variables, err
}

const importCurlRequest = `-- name: ImportCurlRequest :one
INSERT INTO requests (collection_id, name, method, url, headers, params, path_vars, body, auth, settings, created_by)
VALUES ($1, $2, $3, $4, $5, '[]', '[]', $6, '{}', '{}', $7)
RETURNING id
`

type ImportCurlRequestParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	Name         string      `json:"name"`
	Method       string      `json:"method"`
	Url          string      `json:"url"`
	Headers      []byte      `json:"headers"`
	Body         []byte      `json:"body"`
	CreatedBy    pgtype.UUID `json:"created_by"`
}

func (q *Queries) ImportCurlRequest(ctx context.Context, arg ImportCurlRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, importCurlRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Body,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const importSharedRequest = `-- name: ImportSharedRequest :one
INSERT INTO requests (collection_id, name, method, url, headers, params, path_vars, body, auth, settings,
                      pre_request_script, test_script, sort_order, description, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15)
RETURNING id
`

type ImportSharedRequestParams struct {
	CollectionID     pgtype.UUID `json:"collection_id"`
	Name             string      `json:"name"`
	Method           string      `json:"method"`
	Url              string      `json:"url"`
	Headers          []byte      `json:"headers"`
	Params           []byte      `json:"params"`
	PathVars         []byte      `json:"path_vars"`
	Body             []byte      `json:"body"`
	Auth             []byte      `json:"auth"`
	Settings         []byte      `json:"settings"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	SortOrder        int32       `json:"sort_order"`
	Description      string      `json:"description"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

func (q *Queries) ImportSharedRequest(ctx context.Context, arg ImportSharedRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, importSharedRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SortOrder,
		arg.Description,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertImportedRequest = `-- name: InsertImportedRequest :exec
INSERT INTO requests (collection_id, name, method, url, headers, params, path_vars, body, auth, settings, pre_request_script, test_script, sort_order, description, source_operation_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
`

type InsertImportedRequestParams struct {
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	Settings          []byte      `json:"settings"`
	PreRequestScript  string      `json:"pre_request_script"`
	TestScript        string      `json:"test_script"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	SourceOperationID string      `json:"source_operation_id"`
	CreatedBy         pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertImportedRequest(ctx context.Context, arg InsertImportedRequestParams) error {
	_, err := q.db.Exec(ctx, insertImportedRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SortOrder,
		arg.Description,
		arg.SourceOperationID,
		arg.CreatedBy,
	)
	return err
}

const insertSyncedRequest = `-- name: InsertSyncedRequest :exec
INSERT INTO requests (
    collection_id, name, method, url,
    headers, params, path_vars, body, auth, settings,
    sort_order, description,
    source_spec_id, source_operation_id, source_op_hash,
    api_doc, created_by
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10,
    $11, $12,
    $13, $14, $15,
    $16, $17
)
`

type InsertSyncedRequestParams struct {
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	Settings          []byte      `json:"settings"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	ApiDoc            []byte      `json:"api_doc"`
	CreatedBy         pgtype.UUID `json:"created_by"`
}

func (q *Queries) InsertSyncedRequest(ctx context.Context, arg InsertSyncedRequestParams) error {
	_, err := q.db.Exec(ctx, insertSyncedRequest,
		arg.CollectionID,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.SortOrder,
		arg.Description,
		arg.SourceSpecID,
		arg.SourceOperationID,
		arg.SourceOpHash,
		arg.ApiDoc,
		arg.CreatedBy,
	)
	return err
}

const listCatalogEndpointsByWorkspace = `-- name: ListCatalogEndpointsByWorkspace :many
SELECT r.id, r.collection_id, c.name, r.name, r.method, r.url, r.description,
       COALESCE(r.api_doc, '{}'), r.source_spec_id,
       COALESCE(r.source_operation_id, '')
FROM requests r
JOIN collections c ON c.id = r.collection_id
WHERE c.workspace_id = $1
ORDER BY c.sort_order, c.name, r.sort_order
`

type ListCatalogEndpointsByWorkspaceRow struct {
	ID                pgtype.UUID `json:"id"`
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Name_2            string      `json:"name_2"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Description       string      `json:"description"`
	ApiDoc            []byte      `json:"api_doc"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
}

func (q *Queries) ListCatalogEndpointsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListCatalogEndpointsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listCatalogEndpointsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogEndpointsByWorkspaceRow{}
	for rows.Next() {
		var i ListCatalogEndpointsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Name_2,
			&i.Method,
			&i.Url,
			&i.Description,
			&i.ApiDoc,
			&i.SourceSpecID,
			&i.SourceOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogEndpointsByWorkspaceAndCollection = `-- name: ListCatalogEndpointsByWorkspaceAndCollection :many
SELECT r.id, r.collection_id, c.name, r.name, r.method, r.url, r.description,
       COALESCE(r.api_doc, '{}'), r.source_spec_id,
       COALESCE(r.source_operation_id, '')
FROM requests r
JOIN collections c ON c.id = r.collection_id
WHERE c.workspace_id = $1 AND r.collection_id = $2
ORDER BY c.sort_order, c.name, r.sort_order
`

type ListCatalogEndpointsByWorkspaceAndCollectionParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

type ListCatalogEndpointsByWorkspaceAndCollectionRow struct {
	ID                pgtype.UUID `json:"id"`
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Name_2            string      `json:"name_2"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Description       string      `json:"description"`
	ApiDoc            []byte      `json:"api_doc"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
}

func (q *Queries) ListCatalogEndpointsByWorkspaceAndCollection(ctx context.Context, arg ListCatalogEndpointsByWorkspaceAndCollectionParams) ([]ListCatalogEndpointsByWorkspaceAndCollectionRow, error) {
	rows, err := q.db.Query(ctx, listCatalogEndpointsByWorkspaceAndCollection, arg.WorkspaceID, arg.CollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogEndpointsByWorkspaceAndCollectionRow{}
	for rows.Next() {
		var i ListCatalogEndpointsByWorkspaceAndCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Name_2,
			&i.Method,
			&i.Url,
			&i.Description,
			&i.ApiDoc,
			&i.SourceSpecID,
			&i.SourceOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionDocEndpoints = `-- name: ListCollectionDocEndpoints :many
SELECT id, name, method, url, description, COALESCE(api_doc, '{}'), source_spec_id
FROM requests
WHERE collection_id = $1
ORDER BY sort_order
`

type ListCollectionDocEndpointsRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Method       string      `json:"method"`
	Url          string      `json:"url"`
	Description  string      `json:"description"`
	ApiDoc       []byte      `json:"api_doc"`
	SourceSpecID pgtype.UUID `json:"source_spec_id"`
}

func (q *Queries) ListCollectionDocEndpoints(ctx context.Context, collectionID pgtype.UUID) ([]ListCollectionDocEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listCollectionDocEndpoints, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectionDocEndpointsRow{}
	for rows.Next() {
		var i ListCollectionDocEndpointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Description,
			&i.ApiDoc,
			&i.SourceSpecID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentVariablesForExecutor = `-- name: ListEnvironmentVariablesForExecutor :many
SELECT key, value_encrypted, is_secret, phase, enabled
FROM environment_variables
WHERE environment_id = $1
`

type ListEnvironmentVariablesForExecutorRow struct {
	Key            string `json:"key"`
	ValueEncrypted string `json:"value_encrypted"`
	IsSecret       bool   `json:"is_secret"`
	Phase          string `json:"phase"`
	Enabled        bool   `json:"enabled"`
}

func (q *Queries) ListEnvironmentVariablesForExecutor(ctx context.Context, environmentID pgtype.UUID) ([]ListEnvironmentVariablesForExecutorRow, error) {
	rows, err := q.db.Query(ctx, listEnvironmentVariablesForExecutor, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnvironmentVariablesForExecutorRow{}
	for rows.Next() {
		var i ListEnvironmentVariablesForExecutorRow
		if err := rows.Scan(
			&i.Key,
			&i.ValueEncrypted,
			&i.IsSecret,
			&i.Phase,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestIDAndNameByCollection = `-- name: ListRequestIDAndNameByCollection :many
SELECT id, name
FROM requests
WHERE collection_id = $1
ORDER BY sort_order
`

type ListRequestIDAndNameByCollectionRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListRequestIDAndNameByCollection(ctx context.Context, collectionID pgtype.UUID) ([]ListRequestIDAndNameByCollectionRow, error) {
	rows, err := q.db.Query(ctx, listRequestIDAndNameByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestIDAndNameByCollectionRow{}
	for rows.Next() {
		var i ListRequestIDAndNameByCollectionRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestIDsByCollection = `-- name: ListRequestIDsByCollection :many
SELECT id
FROM requests
WHERE collection_id = $1
ORDER BY sort_order
`

func (q *Queries) ListRequestIDsByCollection(ctx context.Context, collectionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRequestIDsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestIDsByOperationInWorkspace = `-- name: ListRequestIDsByOperationInWorkspace :many
SELECT r.id
FROM requests r
JOIN collections c ON c.id = r.collection_id
WHERE c.workspace_id = $1 AND r.source_operation_id = $2
`

type ListRequestIDsByOperationInWorkspaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	OperationID string      `json:"operation_id"`
}

func (q *Queries) ListRequestIDsByOperationInWorkspace(ctx context.Context, arg ListRequestIDsByOperationInWorkspaceParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRequestIDsByOperationInWorkspace, arg.WorkspaceID, arg.OperationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestIDsByTemplate = `-- name: ListRequestIDsByTemplate :many
SELECT id
FROM requests
WHERE template_id = $1
`

func (q *Queries) ListRequestIDsByTemplate(ctx context.Context, templateID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listRequestIDsByTemplate, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByCollection = `-- name: ListRequestsByCollection :many
SELECT id, collection_id, name, method, url, headers, params, path_vars, body, auth, settings,
       pre_request_script, test_script, sort_order, description, template_id, is_template,
       COALESCE(overridden_fields, '{}'), source_spec_id,
       COALESCE(source_operation_id, ''), COALESCE(source_op_hash, ''),
       COALESCE(api_doc, '{}'), docs_overridden
FROM requests
WHERE collection_id = $1
ORDER BY sort_order
`

type ListRequestsByCollectionRow struct {
	ID                pgtype.UUID `json:"id"`
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	Settings          []byte      `json:"settings"`
	PreRequestScript  string      `json:"pre_request_script"`
	TestScript        string      `json:"test_script"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	TemplateID        pgtype.UUID `json:"template_id"`
	IsTemplate        bool        `json:"is_template"`
	OverriddenFields  []string    `json:"overridden_fields"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	ApiDoc            []byte      `json:"api_doc"`
	DocsOverridden    bool        `json:"docs_overridden"`
}

func (q *Queries) ListRequestsByCollection(ctx context.Context, collectionID pgtype.UUID) ([]ListRequestsByCollectionRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByCollectionRow{}
	for rows.Next() {
		var i ListRequestsByCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Params,
			&i.PathVars,
			&i.Body,
			&i.Auth,
			&i.Settings,
			&i.PreRequestScript,
			&i.TestScript,
			&i.SortOrder,
			&i.Description,
			&i.TemplateID,
			&i.IsTemplate,
			&i.OverriddenFields,
			&i.SourceSpecID,
			&i.SourceOperationID,
			&i.SourceOpHash,
			&i.ApiDoc,
			&i.DocsOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByWorkspace = `-- name: ListRequestsByWorkspace :many
SELECT r.id, r.collection_id, r.name, r.method, r.url, r.headers, r.params, r.path_vars, r.body, r.auth, r.settings,
       r.pre_request_script, r.test_script, r.sort_order, r.description, r.template_id, r.is_template,
       COALESCE(r.overridden_fields, '{}'), r.source_spec_id,
       COALESCE(r.source_operation_id, ''), COALESCE(r.source_op_hash, ''),
       COALESCE(r.api_doc, '{}'), r.docs_overridden
FROM requests r
JOIN collections c ON c.id = r.collection_id
WHERE c.workspace_id = $1
ORDER BY c.sort_order, c.name, r.sort_order
`

type ListRequestsByWorkspaceRow struct {
	ID                pgtype.UUID `json:"id"`
	CollectionID      pgtype.UUID `json:"collection_id"`
	Name              string      `json:"name"`
	Method            string      `json:"method"`
	Url               string      `json:"url"`
	Headers           []byte      `json:"headers"`
	Params            []byte      `json:"params"`
	PathVars          []byte      `json:"path_vars"`
	Body              []byte      `json:"body"`
	Auth              []byte      `json:"auth"`
	Settings          []byte      `json:"settings"`
	PreRequestScript  string      `json:"pre_request_script"`
	TestScript        string      `json:"test_script"`
	SortOrder         int32       `json:"sort_order"`
	Description       string      `json:"description"`
	TemplateID        pgtype.UUID `json:"template_id"`
	IsTemplate        bool        `json:"is_template"`
	OverriddenFields  []string    `json:"overridden_fields"`
	SourceSpecID      pgtype.UUID `json:"source_spec_id"`
	SourceOperationID string      `json:"source_operation_id"`
	SourceOpHash      string      `json:"source_op_hash"`
	ApiDoc            []byte      `json:"api_doc"`
	DocsOverridden    bool        `json:"docs_overridden"`
}

func (q *Queries) ListRequestsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListRequestsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByWorkspaceRow{}
	for rows.Next() {
		var i ListRequestsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Params,
			&i.PathVars,
			&i.Body,
			&i.Auth,
			&i.Settings,
			&i.PreRequestScript,
			&i.TestScript,
			&i.SortOrder,
			&i.Description,
			&i.TemplateID,
			&i.IsTemplate,
			&i.OverriddenFields,
			&i.SourceSpecID,
			&i.SourceOperationID,
			&i.SourceOpHash,
			&i.ApiDoc,
			&i.DocsOverridden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForCatalogShare = `-- name: ListRequestsForCatalogShare :many
SELECT r.id, r.name, r.method, r.url, r.description, COALESCE(r.api_doc, '{}')
FROM requests r
WHERE r.collection_id = $1
ORDER BY r.sort_order
`

type ListRequestsForCatalogShareRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Method      string      `json:"method"`
	Url         string      `json:"url"`
	Description string      `json:"description"`
	ApiDoc      []byte      `json:"api_doc"`
}

func (q *Queries) ListRequestsForCatalogShare(ctx context.Context, collectionID pgtype.UUID) ([]ListRequestsForCatalogShareRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForCatalogShare, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsForCatalogShareRow{}
	for rows.Next() {
		var i ListRequestsForCatalogShareRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Description,
			&i.ApiDoc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForDuplicate = `-- name: ListRequestsForDuplicate :many
SELECT id, collection_id, name, method, url, headers, params, path_vars, body, auth, settings,
       pre_request_script, test_script, sort_order, description
FROM requests
WHERE collection_id = $1
`

type ListRequestsForDuplicateRow struct {
	ID               pgtype.UUID `json:"id"`
	CollectionID     pgtype.UUID `json:"collection_id"`
	Name             string      `json:"name"`
	Method           string      `json:"method"`
	Url              string      `json:"url"`
	Headers          []byte      `json:"headers"`
	Params           []byte      `json:"params"`
	PathVars         []byte      `json:"path_vars"`
	Body             []byte      `json:"body"`
	Auth             []byte      `json:"auth"`
	Settings         []byte      `json:"settings"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	SortOrder        int32       `json:"sort_order"`
	Description      string      `json:"description"`
}

func (q *Queries) ListRequestsForDuplicate(ctx context.Context, collectionID pgtype.UUID) ([]ListRequestsForDuplicateRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForDuplicate, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsForDuplicateRow{}
	for rows.Next() {
		var i ListRequestsForDuplicateRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Params,
			&i.PathVars,
			&i.Body,
			&i.Auth,
			&i.Settings,
			&i.PreRequestScript,
			&i.TestScript,
			&i.SortOrder,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForExport = `-- name: ListRequestsForExport :many
SELECT name, method, url, headers, body, pre_request_script, test_script, sort_order, description
FROM requests
WHERE collection_id = $1
ORDER BY sort_order
`

type ListRequestsForExportRow struct {
	Name             string `json:"name"`
	Method           string `json:"method"`
	Url              string `json:"url"`
	Headers          []byte `json:"headers"`
	Body             []byte `json:"body"`
	PreRequestScript string `json:"pre_request_script"`
	TestScript       string `json:"test_script"`
	SortOrder        int32  `json:"sort_order"`
	Description      string `json:"description"`
}

func (q *Queries) ListRequestsForExport(ctx context.Context, collectionID pgtype.UUID) ([]ListRequestsForExportRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForExport, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsForExportRow{}
	for rows.Next() {
		var i ListRequestsForExportRow
		if err := rows.Scan(
			&i.Name,
			&i.Method,
			&i.Url,
			&i.Headers,
			&i.Body,
			&i.PreRequestScript,
			&i.TestScript,
			&i.SortOrder,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForOperationBackfill = `-- name: ListRequestsForOperationBackfill :many
SELECT r.id, r.method, r.url
FROM requests r
JOIN collections c ON c.id = r.collection_id
WHERE c.workspace_id = $1
  AND r.source_operation_id = ''
  AND r.source_spec_id IS NULL
`

type ListRequestsForOperationBackfillRow struct {
	ID     pgtype.UUID `json:"id"`
	Method string      `json:"method"`
	Url    string      `json:"url"`
}

func (q *Queries) ListRequestsForOperationBackfill(ctx context.Context, workspaceID pgtype.UUID) ([]ListRequestsForOperationBackfillRow, error) {
	rows, err := q.db.Query(ctx, listRequestsForOperationBackfill, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsForOperationBackfillRow{}
	for rows.Next() {
		var i ListRequestsForOperationBackfillRow
		if err := rows.Scan(&i.ID, &i.Method, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateChildOverriddenFields = `-- name: ListTemplateChildOverriddenFields :many
SELECT id, overridden_fields
FROM requests
WHERE template_id = $1
`

type ListTemplateChildOverriddenFieldsRow struct {
	ID               pgtype.UUID `json:"id"`
	OverriddenFields []string    `json:"overridden_fields"`
}

func (q *Queries) ListTemplateChildOverriddenFields(ctx context.Context, templateID pgtype.UUID) ([]ListTemplateChildOverriddenFieldsRow, error) {
	rows, err := q.db.Query(ctx, listTemplateChildOverriddenFields, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateChildOverriddenFieldsRow{}
	for rows.Next() {
		var i ListTemplateChildOverriddenFieldsRow
		if err := rows.Scan(&i.ID, &i.OverriddenFields); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveRequest = `-- name: MoveRequest :exec
UPDATE requests
SET collection_id = $1,
    sort_order = $2,
    updated_at = now()
WHERE id = $3
`

type MoveRequestParams struct {
	CollectionID pgtype.UUID `json:"collection_id"`
	SortOrder    int32       `json:"sort_order"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) MoveRequest(ctx context.Context, arg MoveRequestParams) error {
	_, err := q.db.Exec(ctx, moveRequest, arg.CollectionID, arg.SortOrder, arg.ID)
	return err
}

const promoteRequestToTemplate = `-- name: PromoteRequestToTemplate :exec
UPDATE requests
SET is_template = true,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) PromoteRequestToTemplate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteRequestToTemplate, id)
	return err
}

const snapshotTemplateChild = `-- name: SnapshotTemplateChild :exec
UPDATE requests
SET method = $1,
    url = $2,
    headers = $3,
    params = $4,
    path_vars = $5,
    body = $6,
    auth = $7,
    settings = $8,
    pre_request_script = $9,
    test_script = $10,
    template_id = NULL,
    overridden_fields = $11,
    updated_at = now()
WHERE id = $12
`

type SnapshotTemplateChildParams struct {
	Method           string      `json:"method"`
	Url              string      `json:"url"`
	Headers          []byte      `json:"headers"`
	Params           []byte      `json:"params"`
	PathVars         []byte      `json:"path_vars"`
	Body             []byte      `json:"body"`
	Auth             []byte      `json:"auth"`
	Settings         []byte      `json:"settings"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	OverriddenFields []string    `json:"overridden_fields"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) SnapshotTemplateChild(ctx context.Context, arg SnapshotTemplateChildParams) error {
	_, err := q.db.Exec(ctx, snapshotTemplateChild,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.PreRequestScript,
		arg.TestScript,
		arg.OverriddenFields,
		arg.ID,
	)
	return err
}

const updateRequest = `-- name: UpdateRequest :exec
UPDATE requests
SET name = $1,
    method = $2,
    url = $3,
    headers = $4,
    params = $5,
    path_vars = $6,
    body = $7,
    auth = $8,
    settings = $9,
    pre_request_script = $10,
    test_script = $11,
    sort_order = $12,
    description = $13,
    overridden_fields = $14,
    api_doc = COALESCE($15, api_doc),
    docs_overridden = $16,
    updated_at = now()
WHERE id = $17
`

type UpdateRequestParams struct {
	Name             string      `json:"name"`
	Method           string      `json:"method"`
	Url              string      `json:"url"`
	Headers          []byte      `json:"headers"`
	Params           []byte      `json:"params"`
	PathVars         []byte      `json:"path_vars"`
	Body             []byte      `json:"body"`
	Auth             []byte      `json:"auth"`
	Settings         []byte      `json:"settings"`
	PreRequestScript string      `json:"pre_request_script"`
	TestScript       string      `json:"test_script"`
	SortOrder        int32       `json:"sort_order"`
	Description      string      `json:"description"`
	OverriddenFields []string    `json:"overridden_fields"`
	ApiDoc           []byte      `json:"api_doc"`
	DocsOverridden   bool        `json:"docs_overridden"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) error {
	_, err := q.db.Exec(ctx, updateRequest,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.Params,
		arg.PathVars,
		arg.Body,
		arg.Auth,
		arg.Settings,
		arg.PreRequestScript,
		arg.TestScript,
		arg.SortOrder,
		arg.Description,
		arg.OverriddenFields,
		arg.ApiDoc,
		arg.DocsOverridden,
		arg.ID,
	)
	return err
}

const updateRequestOverriddenFields = `-- name: UpdateRequestOverriddenFields :exec
UPDATE requests
SET overridden_fields = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateRequestOverriddenFieldsParams struct {
	OverriddenFields []string    `json:"overridden_fields"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRequestOverriddenFields(ctx context.Context, arg UpdateRequestOverriddenFieldsParams) error {
	_, err := q.db.Exec(ctx, updateRequestOverriddenFields, arg.OverriddenFields, arg.ID)
	return err
}

const updateRequestSortOrder = `-- name: UpdateRequestSortOrder :exec
UPDATE requests
SET sort_order = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateRequestSortOrderParams struct {
	SortOrder int32       `json:"sort_order"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRequestSortOrder(ctx context.Context, arg UpdateRequestSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateRequestSortOrder, arg.SortOrder, arg.ID)
	return err
}
