// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (workspace_id, kind, source_id, token, title, snapshot, visibility, expires_at, created_by)
VALUES ($1, $2::share_kind, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateShareParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Kind        ShareKind          `json:"kind"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Token       string             `json:"token"`
	Title       string             `json:"title"`
	Snapshot    []byte             `json:"snapshot"`
	Visibility  string             `json:"visibility"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.WorkspaceID,
		arg.Kind,
		arg.SourceID,
		arg.Token,
		arg.Title,
		arg.Snapshot,
		arg.Visibility,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getShareByToken = `-- name: GetShareByToken :one
SELECT id, workspace_id, kind::text, source_id, token, title, snapshot, visibility, expires_at, revoked_at, created_by, created_at
FROM shares
WHERE token = $1
`

type GetShareByTokenRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Kind        string             `json:"kind"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Token       string             `json:"token"`
	Title       string             `json:"title"`
	Snapshot    []byte             `json:"snapshot"`
	Visibility  string             `json:"visibility"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetShareByToken(ctx context.Context, token string) (GetShareByTokenRow, error) {
	row := q.db.QueryRow(ctx, getShareByToken, token)
	var i GetShareByTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.SourceID,
		&i.Token,
		&i.Title,
		&i.Snapshot,
		&i.Visibility,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getShareWorkspaceAndCreator = `-- name: GetShareWorkspaceAndCreator :one
SELECT workspace_id, created_by
FROM shares
WHERE id = $1
`

type GetShareWorkspaceAndCreatorRow struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) GetShareWorkspaceAndCreator(ctx context.Context, id pgtype.UUID) (GetShareWorkspaceAndCreatorRow, error) {
	row := q.db.QueryRow(ctx, getShareWorkspaceAndCreator, id)
	var i GetShareWorkspaceAndCreatorRow
	err := row.Scan(&i.WorkspaceID, &i.CreatedBy)
	return i, err
}

const listActiveShares = `-- name: ListActiveShares :many
SELECT id, workspace_id, kind::text, source_id, token, title, visibility, expires_at, created_by, created_at
FROM shares
WHERE workspace_id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
`

type ListActiveSharesRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Kind        string             `json:"kind"`
	SourceID    pgtype.UUID        `json:"source_id"`
	Token       string             `json:"token"`
	Title       string             `json:"title"`
	Visibility  string             `json:"visibility"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActiveShares(ctx context.Context, workspaceID pgtype.UUID) ([]ListActiveSharesRow, error) {
	rows, err := q.db.Query(ctx, listActiveShares, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSharesRow{}
	for rows.Next() {
		var i ListActiveSharesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.SourceID,
			&i.Token,
			&i.Title,
			&i.Visibility,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShare = `-- name: RevokeShare :exec
UPDATE shares
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeShare(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeShare, id)
	return err
}
