// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: testcase.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTestCaseRequestLink = `-- name: AddTestCaseRequestLink :exec
INSERT INTO test_case_request_links (test_case_id, request_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTestCaseRequestLinkParams struct {
	TestCaseID pgtype.UUID `json:"test_case_id"`
	RequestID  pgtype.UUID `json:"request_id"`
}

func (q *Queries) AddTestCaseRequestLink(ctx context.Context, arg AddTestCaseRequestLinkParams) error {
	_, err := q.db.Exec(ctx, addTestCaseRequestLink, arg.TestCaseID, arg.RequestID)
	return err
}

const createTestCase = `-- name: CreateTestCase :one
INSERT INTO test_cases (workspace_id, title, description, sort_order, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, title, description, sort_order, created_by, created_at, updated_at
`

type CreateTestCaseParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	SortOrder   int32       `json:"sort_order"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTestCase(ctx context.Context, arg CreateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, createTestCase,
		arg.WorkspaceID,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.CreatedBy,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTestCase = `-- name: DeleteTestCase :exec
DELETE FROM test_cases
WHERE id = $1 AND workspace_id = $2
`

type DeleteTestCaseParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteTestCase(ctx context.Context, arg DeleteTestCaseParams) error {
	_, err := q.db.Exec(ctx, deleteTestCase, arg.ID, arg.WorkspaceID)
	return err
}

const getTestCase = `-- name: GetTestCase :one
SELECT id, workspace_id, title, description, sort_order, created_by, created_at, updated_at
FROM test_cases
WHERE id = $1 AND workspace_id = $2
`

type GetTestCaseParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetTestCase(ctx context.Context, arg GetTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, getTestCase, arg.ID, arg.WorkspaceID)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTestCaseRequestLinks = `-- name: ListTestCaseRequestLinks :many
SELECT r.id, r.name, r.method, r.url, c.workspace_id, w.name AS workspace_name
FROM test_case_request_links tcl
JOIN requests r ON r.id = tcl.request_id
JOIN collections c ON c.id = r.collection_id
JOIN workspaces w ON w.id = c.workspace_id
WHERE tcl.test_case_id = $1
`

type ListTestCaseRequestLinksRow struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	Method        string      `json:"method"`
	Url           string      `json:"url"`
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	WorkspaceName string      `json:"workspace_name"`
}

func (q *Queries) ListTestCaseRequestLinks(ctx context.Context, testCaseID pgtype.UUID) ([]ListTestCaseRequestLinksRow, error) {
	rows, err := q.db.Query(ctx, listTestCaseRequestLinks, testCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTestCaseRequestLinksRow{}
	for rows.Next() {
		var i ListTestCaseRequestLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.WorkspaceID,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCases = `-- name: ListTestCases :many
SELECT id, workspace_id, title, description, sort_order, created_by, created_at, updated_at
FROM test_cases
WHERE workspace_id = $1
ORDER BY sort_order ASC, title ASC
`

func (q *Queries) ListTestCases(ctx context.Context, workspaceID pgtype.UUID) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCases, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTestCaseRequestLink = `-- name: RemoveTestCaseRequestLink :exec
DELETE FROM test_case_request_links
WHERE test_case_id = $1 AND request_id = $2
`

type RemoveTestCaseRequestLinkParams struct {
	TestCaseID pgtype.UUID `json:"test_case_id"`
	RequestID  pgtype.UUID `json:"request_id"`
}

func (q *Queries) RemoveTestCaseRequestLink(ctx context.Context, arg RemoveTestCaseRequestLinkParams) error {
	_, err := q.db.Exec(ctx, removeTestCaseRequestLink, arg.TestCaseID, arg.RequestID)
	return err
}

const updateTestCase = `-- name: UpdateTestCase :one
UPDATE test_cases
SET title = COALESCE($1, title),
    description = COALESCE($2, description),
    sort_order = COALESCE($3, sort_order),
    updated_at = now()
WHERE id = $4 AND workspace_id = $5
RETURNING id, workspace_id, title, description, sort_order, created_by, created_at, updated_at
`

type UpdateTestCaseParams struct {
	Title       *string     `json:"title"`
	Description *string     `json:"description"`
	SortOrder   *int32      `json:"sort_order"`
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateTestCase(ctx context.Context, arg UpdateTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, updateTestCase,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.ID,
		arg.WorkspaceID,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyTestCaseInWorkspace = `-- name: VerifyTestCaseInWorkspace :one
SELECT EXISTS(
    SELECT 1 FROM test_cases
    WHERE id = $1 AND workspace_id = $2
) AS exists
`

type VerifyTestCaseInWorkspaceParams struct {
	ID          pgtype.UUID `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) VerifyTestCaseInWorkspace(ctx context.Context, arg VerifyTestCaseInWorkspaceParams) (bool, error) {
	row := q.db.QueryRow(ctx, verifyTestCaseInWorkspace, arg.ID, arg.WorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
