// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspacetoken.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceApiToken = `-- name: CreateWorkspaceApiToken :one
INSERT INTO workspace_api_tokens (workspace_id, name, token_hash, token_prefix, scopes, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateWorkspaceApiTokenParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	TokenHash   string      `json:"token_hash"`
	TokenPrefix string      `json:"token_prefix"`
	Scopes      []string    `json:"scopes"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateWorkspaceApiToken(ctx context.Context, arg CreateWorkspaceApiTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWorkspaceApiToken,
		arg.WorkspaceID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getWorkspaceApiTokenByHash = `-- name: GetWorkspaceApiTokenByHash :one
SELECT workspace_id, scopes, revoked_at
FROM workspace_api_tokens
WHERE token_hash = $1
`

type GetWorkspaceApiTokenByHashRow struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Scopes      []string           `json:"scopes"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetWorkspaceApiTokenByHash(ctx context.Context, tokenHash string) (GetWorkspaceApiTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceApiTokenByHash, tokenHash)
	var i GetWorkspaceApiTokenByHashRow
	err := row.Scan(&i.WorkspaceID, &i.Scopes, &i.RevokedAt)
	return i, err
}

const listWorkspaceApiTokens = `-- name: ListWorkspaceApiTokens :many
SELECT id, workspace_id, name, token_prefix, scopes, created_at, revoked_at
FROM workspace_api_tokens
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListWorkspaceApiTokensRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Name        string             `json:"name"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []string           `json:"scopes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) ListWorkspaceApiTokens(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceApiTokensRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceApiTokens, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceApiTokensRow{}
	for rows.Next() {
		var i ListWorkspaceApiTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.TokenPrefix,
			&i.Scopes,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeWorkspaceApiToken = `-- name: RevokeWorkspaceApiToken :exec
UPDATE workspace_api_tokens
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeWorkspaceApiToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeWorkspaceApiToken, id)
	return err
}
