// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceOwner = `-- name: AddWorkspaceOwner :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, 'owner'::workspace_role)
`

type AddWorkspaceOwnerParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddWorkspaceOwner(ctx context.Context, arg AddWorkspaceOwnerParams) error {
	_, err := q.db.Exec(ctx, addWorkspaceOwner, arg.WorkspaceID, arg.UserID)
	return err
}

const countWorkspaceOwners = `-- name: CountWorkspaceOwners :one
SELECT COUNT(*)
FROM workspace_members
WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountWorkspaceOwners(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :exec
INSERT INTO activity_log (workspace_id, actor_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateActivityLogParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActorID     pgtype.UUID `json:"actor_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) error {
	_, err := q.db.Exec(ctx, createActivityLog,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const createDefaultCollection = `-- name: CreateDefaultCollection :exec
INSERT INTO collections (workspace_id, name, created_by)
VALUES ($1, 'My Collection', $2)
`

type CreateDefaultCollectionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDefaultCollection(ctx context.Context, arg CreateDefaultCollectionParams) error {
	_, err := q.db.Exec(ctx, createDefaultCollection, arg.WorkspaceID, arg.CreatedBy)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name, description, type, created_by)
VALUES ($1, $2, $3::workspace_type, $4)
RETURNING id
`

type CreateWorkspaceParams struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Type        WorkspaceType `json:"type"`
	CreatedBy   pgtype.UUID   `json:"created_by"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.CreatedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces
WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT id
FROM users
WHERE email = $1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, description, type::text, variables
FROM workspaces
WHERE id = $1
`

type GetWorkspaceByIDRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Type        string      `json:"type"`
	Variables   []byte      `json:"variables"`
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (GetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i GetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Variables,
	)
	return i, err
}

const getWorkspaceName = `-- name: GetWorkspaceName :one
SELECT name
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listWorkspaceActivity = `-- name: ListWorkspaceActivity :many
SELECT al.id, al.action, al.entity_type, al.entity_id, al.metadata, al.created_at, u.email
FROM activity_log al
JOIN users u ON u.id = al.actor_id
WHERE al.workspace_id = $1
ORDER BY al.created_at DESC
LIMIT 100
`

type ListWorkspaceActivityRow struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Email      string             `json:"email"`
}

func (q *Queries) ListWorkspaceActivity(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceActivityRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceActivity, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceActivityRow{}
	for rows.Next() {
		var i ListWorkspaceActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT u.id, u.email, u.display_name, wm.role::text
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
`

type ListWorkspaceMembersRow struct {
	ID          pgtype.UUID `json:"id"`
	Email       string      `json:"email"`
	DisplayName string      `json:"display_name"`
	WmRole      string      `json:"wm_role"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.WmRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.id, w.name, w.description, w.type::text, w.variables, wm.role::text, w.created_at
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1
ORDER BY w.created_at DESC
`

type ListWorkspacesByUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	WType       string             `json:"w_type"`
	Variables   []byte             `json:"variables"`
	WmRole      string             `json:"wm_role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID pgtype.UUID) ([]ListWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesByUserRow{}
	for rows.Next() {
		var i ListWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.WType,
			&i.Variables,
			&i.WmRole,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceDescription = `-- name: UpdateWorkspaceDescription :exec
UPDATE workspaces
SET description = $1, updated_at = now()
WHERE id = $2
`

type UpdateWorkspaceDescriptionParams struct {
	Description string      `json:"description"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWorkspaceDescription(ctx context.Context, arg UpdateWorkspaceDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceDescription, arg.Description, arg.ID)
	return err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members
SET role = $1::workspace_role
WHERE workspace_id = $2 AND user_id = $3
`

type UpdateWorkspaceMemberRoleParams struct {
	Role        WorkspaceRole `json:"role"`
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	UserID      pgtype.UUID   `json:"user_id"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.Role, arg.WorkspaceID, arg.UserID)
	return err
}

const updateWorkspaceName = `-- name: UpdateWorkspaceName :exec
UPDATE workspaces
SET name = $1, updated_at = now()
WHERE id = $2
`

type UpdateWorkspaceNameParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWorkspaceName(ctx context.Context, arg UpdateWorkspaceNameParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceName, arg.Name, arg.ID)
	return err
}

const updateWorkspaceVariables = `-- name: UpdateWorkspaceVariables :exec
UPDATE workspaces
SET variables = $1, updated_at = now()
WHERE id = $2
`

type UpdateWorkspaceVariablesParams struct {
	Variables []byte      `json:"variables"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWorkspaceVariables(ctx context.Context, arg UpdateWorkspaceVariablesParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceVariables, arg.Variables, arg.ID)
	return err
}

const upsertWorkspaceMember = `-- name: UpsertWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3::workspace_role)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID   `json:"workspace_id"`
	UserID      pgtype.UUID   `json:"user_id"`
	Role        WorkspaceRole `json:"role"`
}

func (q *Queries) UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const userHasWorkspaceNamed = `-- name: UserHasWorkspaceNamed :one
SELECT EXISTS(
    SELECT 1
    FROM workspaces w
    INNER JOIN workspace_members wm ON wm.workspace_id = w.id
    WHERE wm.user_id = $1
      AND lower(trim(w.name)) = lower(trim($2))
) AS exists
`

type UserHasWorkspaceNamedParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) UserHasWorkspaceNamed(ctx context.Context, arg UserHasWorkspaceNamedParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasWorkspaceNamed, arg.UserID, arg.Name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userHasWorkspaceNamedExcluding = `-- name: UserHasWorkspaceNamedExcluding :one
SELECT EXISTS(
    SELECT 1
    FROM workspaces w
    INNER JOIN workspace_members wm ON wm.workspace_id = w.id
    WHERE wm.user_id = $1
      AND lower(trim(w.name)) = lower(trim($2))
      AND w.id <> $3
) AS exists
`

type UserHasWorkspaceNamedExcludingParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	Name               string      `json:"name"`
	ExcludeWorkspaceID pgtype.UUID `json:"exclude_workspace_id"`
}

func (q *Queries) UserHasWorkspaceNamedExcluding(ctx context.Context, arg UserHasWorkspaceNamedExcludingParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasWorkspaceNamedExcluding, arg.UserID, arg.Name, arg.ExcludeWorkspaceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workspaceExists = `-- name: WorkspaceExists :one
SELECT EXISTS(SELECT 1 FROM workspaces WHERE id = $1)
`

func (q *Queries) WorkspaceExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
