/**
 * Standard and extension HTTP field names (IANA registry + common API headers).
 * Sorted alphabetically; filter with prefix match (case-insensitive).
 */
export const HTTP_HEADER_NAMES: readonly string[] = [
  'A-IM',
  'Accept',
  'Accept-CH',
  'Accept-Charset',
  'Accept-Datetime',
  'Accept-Encoding',
  'Accept-Features',
  'Accept-Language',
  'Accept-Patch',
  'Accept-Post',
  'Accept-Ranges',
  'Access-Control-Allow-Credentials',
  'Access-Control-Allow-Headers',
  'Access-Control-Allow-Methods',
  'Access-Control-Allow-Origin',
  'Access-Control-Expose-Headers',
  'Access-Control-Max-Age',
  'Access-Control-Request-Headers',
  'Access-Control-Request-Method',
  'Age',
  'Allow',
  'ALPN',
  'Alt-Svc',
  'Alt-Used',
  'Api-Key',
  'Authorization',
  'Cache-Control',
  'Cal-Managed-ID',
  'CalDAV-Timezones',
  'Capsule-Protocol',
  'CDN-Loop',
  'Clear-Site-Data',
  'Client-Cert',
  'Client-Cert-Chain',
  'Close',
  'Connection',
  'Content-Digest',
  'Content-Disposition',
  'Content-Encoding',
  'Content-Language',
  'Content-Length',
  'Content-Location',
  'Content-Range',
  'Content-Security-Policy',
  'Content-Security-Policy-Report-Only',
  'Content-Type',
  'Cookie',
  'Cross-Origin-Embedder-Policy',
  'Cross-Origin-Opener-Policy',
  'Cross-Origin-Resource-Policy',
  'DASL',
  'Date',
  'DAV',
  'Delta-Base',
  'Depth',
  'Destination',
  'DNT',
  'Early-Data',
  'ETag',
  'Expect',
  'Expect-CT',
  'Expires',
  'Forwarded',
  'From',
  'Host',
  'If',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Schedule-Tag-Match',
  'If-Unmodified-Since',
  'IM',
  'Keep-Alive',
  'Label',
  'Last-Event-ID',
  'Last-Modified',
  'Link',
  'Location',
  'Lock-Token',
  'Max-Forwards',
  'Memento-Datetime',
  'NEL',
  'OData-EntityId',
  'OData-Isolation',
  'OData-MaxVersion',
  'OData-Version',
  'Optional-WWW-Authenticate',
  'Ordering-Type',
  'Origin',
  'Origin-Agent-Cluster',
  'Overwrite',
  'Permissions-Policy',
  'Ping-From',
  'Ping-To',
  'Position',
  'Prefer',
  'Preference-Applied',
  'Proxy-Authenticate',
  'Proxy-Authorization',
  'Proxy-Status',
  'Public-Key-Pins',
  'Public-Key-Pins-Report-Only',
  'Range',
  'Referer',
  'Referrer-Policy',
  'Replay-Nonce',
  'Report-To',
  'Retry-After',
  'Schedule-Reply',
  'Schedule-Tag',
  'Sec-Browsing-Topics',
  'Sec-CH-Prefers-Color-Scheme',
  'Sec-CH-Prefers-Reduced-Motion',
  'Sec-CH-UA',
  'Sec-CH-UA-Arch',
  'Sec-CH-UA-Bitness',
  'Sec-CH-UA-Full-Version',
  'Sec-CH-UA-Full-Version-List',
  'Sec-CH-UA-Mobile',
  'Sec-CH-UA-Model',
  'Sec-CH-UA-Platform',
  'Sec-CH-UA-Platform-Version',
  'Sec-CH-UA-WoW64',
  'Sec-Fetch-Dest',
  'Sec-Fetch-Mode',
  'Sec-Fetch-Site',
  'Sec-Fetch-User',
  'Sec-Purpose',
  'Sec-WebSocket-Accept',
  'Sec-WebSocket-Extensions',
  'Sec-WebSocket-Key',
  'Sec-WebSocket-Protocol',
  'Sec-WebSocket-Version',
  'Server',
  'Set-Cookie',
  'SLUG',
  'Status-URI',
  'Strict-Transport-Security',
  'Sunset',
  'Surrogate-Control',
  'Surrogate-Key',
  'TE',
  'Timeout',
  'Timing-Allow-Origin',
  'Trailer',
  'Transfer-Encoding',
  'TTL',
  'Upgrade',
  'Upgrade-Insecure-Requests',
  'User-Agent',
  'Variant-Vary',
  'Vary',
  'Via',
  'Want-Digest',
  'Warning',
  'WWW-Authenticate',
  'X-Amz-Date',
  'X-Amz-Security-Token',
  'X-Api-Key',
  'X-Auth-Token',
  'X-Content-Type-Options',
  'X-Correlation-ID',
  'X-CSRF-Token',
  'X-Forwarded-For',
  'X-Forwarded-Host',
  'X-Forwarded-Proto',
  'X-Frame-Options',
  'X-Real-IP',
  'X-Request-ID',
  'X-XSS-Protection',
] as const

export function filterHttpHeaders(query: string, limit = 50): string[] {
  const q = query.trim()
  if (!q) return HTTP_HEADER_NAMES.slice(0, limit) as string[]

  const lower = q.toLowerCase()
  const prefix: string[] = []
  const contains: string[] = []

  for (const name of HTTP_HEADER_NAMES) {
    const nl = name.toLowerCase()
    if (nl.startsWith(lower)) {
      prefix.push(name)
    } else if (nl.includes(lower)) {
      contains.push(name)
    }
    if (prefix.length + contains.length >= limit * 2) break
  }

  return [...prefix, ...contains].slice(0, limit)
}
